/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Moved type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Moved{}

// Moved Present if message was moved to Trash
type Moved struct {
	// Trash folder path
	Destination string `json:"destination"`
	// Message ID in Trash
	Message string `json:"message"`
}

type _Moved Moved

// NewMoved instantiates a new Moved object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMoved(destination string, message string) *Moved {
	this := Moved{}
	this.Destination = destination
	this.Message = message
	return &this
}

// NewMovedWithDefaults instantiates a new Moved object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMovedWithDefaults() *Moved {
	this := Moved{}
	return &this
}

// GetDestination returns the Destination field value
func (o *Moved) GetDestination() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Destination
}

// GetDestinationOk returns a tuple with the Destination field value
// and a boolean to check if the value has been set.
func (o *Moved) GetDestinationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Destination, true
}

// SetDestination sets field value
func (o *Moved) SetDestination(v string) {
	o.Destination = v
}

// GetMessage returns the Message field value
func (o *Moved) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *Moved) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *Moved) SetMessage(v string) {
	o.Message = v
}

func (o Moved) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Moved) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["destination"] = o.Destination
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *Moved) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"destination",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMoved := _Moved{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMoved)

	if err != nil {
		return err
	}

	*o = Moved(varMoved)

	return err
}

type NullableMoved struct {
	value *Moved
	isSet bool
}

func (v NullableMoved) Get() *Moved {
	return v.value
}

func (v *NullableMoved) Set(val *Moved) {
	v.value = val
	v.isSet = true
}

func (v NullableMoved) IsSet() bool {
	return v.isSet
}

func (v *NullableMoved) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMoved(val *Moved) *NullableMoved {
	return &NullableMoved{value: val, isSet: true}
}

func (v NullableMoved) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMoved) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


