/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the BounceEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BounceEntry{}

// BounceEntry struct for BounceEntry
type BounceEntry struct {
	// Bounce action (failed, delayed, etc.)
	Action *string `json:"action,omitempty"`
	// When the bounce was detected
	Date *time.Time `json:"date,omitempty"`
	// EmailEngine identifier of the bounce notification
	Message string `json:"message"`
	// Email address that bounced
	Recipient *string `json:"recipient,omitempty"`
	Response *BounceResponse `json:"response,omitempty"`
}

type _BounceEntry BounceEntry

// NewBounceEntry instantiates a new BounceEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBounceEntry(message string) *BounceEntry {
	this := BounceEntry{}
	this.Message = message
	return &this
}

// NewBounceEntryWithDefaults instantiates a new BounceEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBounceEntryWithDefaults() *BounceEntry {
	this := BounceEntry{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *BounceEntry) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BounceEntry) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *BounceEntry) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *BounceEntry) SetAction(v string) {
	o.Action = &v
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *BounceEntry) GetDate() time.Time {
	if o == nil || IsNil(o.Date) {
		var ret time.Time
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BounceEntry) GetDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *BounceEntry) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given time.Time and assigns it to the Date field.
func (o *BounceEntry) SetDate(v time.Time) {
	o.Date = &v
}

// GetMessage returns the Message field value
func (o *BounceEntry) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *BounceEntry) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *BounceEntry) SetMessage(v string) {
	o.Message = v
}

// GetRecipient returns the Recipient field value if set, zero value otherwise.
func (o *BounceEntry) GetRecipient() string {
	if o == nil || IsNil(o.Recipient) {
		var ret string
		return ret
	}
	return *o.Recipient
}

// GetRecipientOk returns a tuple with the Recipient field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BounceEntry) GetRecipientOk() (*string, bool) {
	if o == nil || IsNil(o.Recipient) {
		return nil, false
	}
	return o.Recipient, true
}

// HasRecipient returns a boolean if a field has been set.
func (o *BounceEntry) HasRecipient() bool {
	if o != nil && !IsNil(o.Recipient) {
		return true
	}

	return false
}

// SetRecipient gets a reference to the given string and assigns it to the Recipient field.
func (o *BounceEntry) SetRecipient(v string) {
	o.Recipient = &v
}

// GetResponse returns the Response field value if set, zero value otherwise.
func (o *BounceEntry) GetResponse() BounceResponse {
	if o == nil || IsNil(o.Response) {
		var ret BounceResponse
		return ret
	}
	return *o.Response
}

// GetResponseOk returns a tuple with the Response field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BounceEntry) GetResponseOk() (*BounceResponse, bool) {
	if o == nil || IsNil(o.Response) {
		return nil, false
	}
	return o.Response, true
}

// HasResponse returns a boolean if a field has been set.
func (o *BounceEntry) HasResponse() bool {
	if o != nil && !IsNil(o.Response) {
		return true
	}

	return false
}

// SetResponse gets a reference to the given BounceResponse and assigns it to the Response field.
func (o *BounceEntry) SetResponse(v BounceResponse) {
	o.Response = &v
}

func (o BounceEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BounceEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	toSerialize["message"] = o.Message
	if !IsNil(o.Recipient) {
		toSerialize["recipient"] = o.Recipient
	}
	if !IsNil(o.Response) {
		toSerialize["response"] = o.Response
	}
	return toSerialize, nil
}

func (o *BounceEntry) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBounceEntry := _BounceEntry{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBounceEntry)

	if err != nil {
		return err
	}

	*o = BounceEntry(varBounceEntry)

	return err
}

type NullableBounceEntry struct {
	value *BounceEntry
	isSet bool
}

func (v NullableBounceEntry) Get() *BounceEntry {
	return v.value
}

func (v *NullableBounceEntry) Set(val *BounceEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableBounceEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableBounceEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBounceEntry(val *BounceEntry) *NullableBounceEntry {
	return &NullableBounceEntry{value: val, isSet: true}
}

func (v NullableBounceEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBounceEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


