/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the WebhookRoutesListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookRoutesListResponse{}

// WebhookRoutesListResponse struct for WebhookRoutesListResponse
type WebhookRoutesListResponse struct {
	// Current page (0-based index)
	Page *int32 `json:"page,omitempty"`
	// Total page count
	Pages *int32 `json:"pages,omitempty"`
	// How many matching entries
	Total *int32 `json:"total,omitempty"`
	Webhooks []WebhookRoutesListEntry `json:"webhooks,omitempty"`
}

// NewWebhookRoutesListResponse instantiates a new WebhookRoutesListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookRoutesListResponse() *WebhookRoutesListResponse {
	this := WebhookRoutesListResponse{}
	return &this
}

// NewWebhookRoutesListResponseWithDefaults instantiates a new WebhookRoutesListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookRoutesListResponseWithDefaults() *WebhookRoutesListResponse {
	this := WebhookRoutesListResponse{}
	return &this
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *WebhookRoutesListResponse) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookRoutesListResponse) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *WebhookRoutesListResponse) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *WebhookRoutesListResponse) SetPage(v int32) {
	o.Page = &v
}

// GetPages returns the Pages field value if set, zero value otherwise.
func (o *WebhookRoutesListResponse) GetPages() int32 {
	if o == nil || IsNil(o.Pages) {
		var ret int32
		return ret
	}
	return *o.Pages
}

// GetPagesOk returns a tuple with the Pages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookRoutesListResponse) GetPagesOk() (*int32, bool) {
	if o == nil || IsNil(o.Pages) {
		return nil, false
	}
	return o.Pages, true
}

// HasPages returns a boolean if a field has been set.
func (o *WebhookRoutesListResponse) HasPages() bool {
	if o != nil && !IsNil(o.Pages) {
		return true
	}

	return false
}

// SetPages gets a reference to the given int32 and assigns it to the Pages field.
func (o *WebhookRoutesListResponse) SetPages(v int32) {
	o.Pages = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *WebhookRoutesListResponse) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookRoutesListResponse) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *WebhookRoutesListResponse) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *WebhookRoutesListResponse) SetTotal(v int32) {
	o.Total = &v
}

// GetWebhooks returns the Webhooks field value if set, zero value otherwise.
func (o *WebhookRoutesListResponse) GetWebhooks() []WebhookRoutesListEntry {
	if o == nil || IsNil(o.Webhooks) {
		var ret []WebhookRoutesListEntry
		return ret
	}
	return o.Webhooks
}

// GetWebhooksOk returns a tuple with the Webhooks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookRoutesListResponse) GetWebhooksOk() ([]WebhookRoutesListEntry, bool) {
	if o == nil || IsNil(o.Webhooks) {
		return nil, false
	}
	return o.Webhooks, true
}

// HasWebhooks returns a boolean if a field has been set.
func (o *WebhookRoutesListResponse) HasWebhooks() bool {
	if o != nil && !IsNil(o.Webhooks) {
		return true
	}

	return false
}

// SetWebhooks gets a reference to the given []WebhookRoutesListEntry and assigns it to the Webhooks field.
func (o *WebhookRoutesListResponse) SetWebhooks(v []WebhookRoutesListEntry) {
	o.Webhooks = v
}

func (o WebhookRoutesListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookRoutesListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.Pages) {
		toSerialize["pages"] = o.Pages
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Webhooks) {
		toSerialize["webhooks"] = o.Webhooks
	}
	return toSerialize, nil
}

type NullableWebhookRoutesListResponse struct {
	value *WebhookRoutesListResponse
	isSet bool
}

func (v NullableWebhookRoutesListResponse) Get() *WebhookRoutesListResponse {
	return v.value
}

func (v *NullableWebhookRoutesListResponse) Set(val *WebhookRoutesListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookRoutesListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookRoutesListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookRoutesListResponse(val *WebhookRoutesListResponse) *NullableWebhookRoutesListResponse {
	return &NullableWebhookRoutesListResponse{value: val, isSet: true}
}

func (v NullableWebhookRoutesListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookRoutesListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


