/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the GatewayResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayResponse{}

// GatewayResponse struct for GatewayResponse
type GatewayResponse struct {
	// Count of email deliveries using this gateway
	Deliveries *int32 `json:"deliveries,omitempty"`
	// Gateway ID
	Gateway string `json:"gateway"`
	// Hostname to connect to
	Host *string `json:"host,omitempty"`
	LastError NullableAccountErrorEntry `json:"lastError,omitempty"`
	// Last delivery time
	LastUse *time.Time `json:"lastUse,omitempty"`
	// Display name for the gateway
	Name string `json:"name"`
	// SMTP authentication password
	Pass *string `json:"pass,omitempty"`
	// Service port number
	Port *int32 `json:"port,omitempty"`
	// Should connection use TLS. Usually true for port 465
	Secure *bool `json:"secure,omitempty"`
	// SMTP authentication username
	User *string `json:"user,omitempty"`
}

type _GatewayResponse GatewayResponse

// NewGatewayResponse instantiates a new GatewayResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayResponse(gateway string, name string) *GatewayResponse {
	this := GatewayResponse{}
	this.Gateway = gateway
	this.Name = name
	var secure bool = false
	this.Secure = &secure
	return &this
}

// NewGatewayResponseWithDefaults instantiates a new GatewayResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayResponseWithDefaults() *GatewayResponse {
	this := GatewayResponse{}
	var secure bool = false
	this.Secure = &secure
	return &this
}

// GetDeliveries returns the Deliveries field value if set, zero value otherwise.
func (o *GatewayResponse) GetDeliveries() int32 {
	if o == nil || IsNil(o.Deliveries) {
		var ret int32
		return ret
	}
	return *o.Deliveries
}

// GetDeliveriesOk returns a tuple with the Deliveries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayResponse) GetDeliveriesOk() (*int32, bool) {
	if o == nil || IsNil(o.Deliveries) {
		return nil, false
	}
	return o.Deliveries, true
}

// HasDeliveries returns a boolean if a field has been set.
func (o *GatewayResponse) HasDeliveries() bool {
	if o != nil && !IsNil(o.Deliveries) {
		return true
	}

	return false
}

// SetDeliveries gets a reference to the given int32 and assigns it to the Deliveries field.
func (o *GatewayResponse) SetDeliveries(v int32) {
	o.Deliveries = &v
}

// GetGateway returns the Gateway field value
func (o *GatewayResponse) GetGateway() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Gateway
}

// GetGatewayOk returns a tuple with the Gateway field value
// and a boolean to check if the value has been set.
func (o *GatewayResponse) GetGatewayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Gateway, true
}

// SetGateway sets field value
func (o *GatewayResponse) SetGateway(v string) {
	o.Gateway = v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *GatewayResponse) GetHost() string {
	if o == nil || IsNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayResponse) GetHostOk() (*string, bool) {
	if o == nil || IsNil(o.Host) {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *GatewayResponse) HasHost() bool {
	if o != nil && !IsNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *GatewayResponse) SetHost(v string) {
	o.Host = &v
}

// GetLastError returns the LastError field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GatewayResponse) GetLastError() AccountErrorEntry {
	if o == nil || IsNil(o.LastError.Get()) {
		var ret AccountErrorEntry
		return ret
	}
	return *o.LastError.Get()
}

// GetLastErrorOk returns a tuple with the LastError field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GatewayResponse) GetLastErrorOk() (*AccountErrorEntry, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastError.Get(), o.LastError.IsSet()
}

// HasLastError returns a boolean if a field has been set.
func (o *GatewayResponse) HasLastError() bool {
	if o != nil && o.LastError.IsSet() {
		return true
	}

	return false
}

// SetLastError gets a reference to the given NullableAccountErrorEntry and assigns it to the LastError field.
func (o *GatewayResponse) SetLastError(v AccountErrorEntry) {
	o.LastError.Set(&v)
}
// SetLastErrorNil sets the value for LastError to be an explicit nil
func (o *GatewayResponse) SetLastErrorNil() {
	o.LastError.Set(nil)
}

// UnsetLastError ensures that no value is present for LastError, not even an explicit nil
func (o *GatewayResponse) UnsetLastError() {
	o.LastError.Unset()
}

// GetLastUse returns the LastUse field value if set, zero value otherwise.
func (o *GatewayResponse) GetLastUse() time.Time {
	if o == nil || IsNil(o.LastUse) {
		var ret time.Time
		return ret
	}
	return *o.LastUse
}

// GetLastUseOk returns a tuple with the LastUse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayResponse) GetLastUseOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastUse) {
		return nil, false
	}
	return o.LastUse, true
}

// HasLastUse returns a boolean if a field has been set.
func (o *GatewayResponse) HasLastUse() bool {
	if o != nil && !IsNil(o.LastUse) {
		return true
	}

	return false
}

// SetLastUse gets a reference to the given time.Time and assigns it to the LastUse field.
func (o *GatewayResponse) SetLastUse(v time.Time) {
	o.LastUse = &v
}

// GetName returns the Name field value
func (o *GatewayResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GatewayResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GatewayResponse) SetName(v string) {
	o.Name = v
}

// GetPass returns the Pass field value if set, zero value otherwise.
func (o *GatewayResponse) GetPass() string {
	if o == nil || IsNil(o.Pass) {
		var ret string
		return ret
	}
	return *o.Pass
}

// GetPassOk returns a tuple with the Pass field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayResponse) GetPassOk() (*string, bool) {
	if o == nil || IsNil(o.Pass) {
		return nil, false
	}
	return o.Pass, true
}

// HasPass returns a boolean if a field has been set.
func (o *GatewayResponse) HasPass() bool {
	if o != nil && !IsNil(o.Pass) {
		return true
	}

	return false
}

// SetPass gets a reference to the given string and assigns it to the Pass field.
func (o *GatewayResponse) SetPass(v string) {
	o.Pass = &v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *GatewayResponse) GetPort() int32 {
	if o == nil || IsNil(o.Port) {
		var ret int32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayResponse) GetPortOk() (*int32, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *GatewayResponse) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given int32 and assigns it to the Port field.
func (o *GatewayResponse) SetPort(v int32) {
	o.Port = &v
}

// GetSecure returns the Secure field value if set, zero value otherwise.
func (o *GatewayResponse) GetSecure() bool {
	if o == nil || IsNil(o.Secure) {
		var ret bool
		return ret
	}
	return *o.Secure
}

// GetSecureOk returns a tuple with the Secure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayResponse) GetSecureOk() (*bool, bool) {
	if o == nil || IsNil(o.Secure) {
		return nil, false
	}
	return o.Secure, true
}

// HasSecure returns a boolean if a field has been set.
func (o *GatewayResponse) HasSecure() bool {
	if o != nil && !IsNil(o.Secure) {
		return true
	}

	return false
}

// SetSecure gets a reference to the given bool and assigns it to the Secure field.
func (o *GatewayResponse) SetSecure(v bool) {
	o.Secure = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *GatewayResponse) GetUser() string {
	if o == nil || IsNil(o.User) {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayResponse) GetUserOk() (*string, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *GatewayResponse) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *GatewayResponse) SetUser(v string) {
	o.User = &v
}

func (o GatewayResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Deliveries) {
		toSerialize["deliveries"] = o.Deliveries
	}
	toSerialize["gateway"] = o.Gateway
	if !IsNil(o.Host) {
		toSerialize["host"] = o.Host
	}
	if o.LastError.IsSet() {
		toSerialize["lastError"] = o.LastError.Get()
	}
	if !IsNil(o.LastUse) {
		toSerialize["lastUse"] = o.LastUse
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Pass) {
		toSerialize["pass"] = o.Pass
	}
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	if !IsNil(o.Secure) {
		toSerialize["secure"] = o.Secure
	}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	return toSerialize, nil
}

func (o *GatewayResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"gateway",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGatewayResponse := _GatewayResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGatewayResponse)

	if err != nil {
		return err
	}

	*o = GatewayResponse(varGatewayResponse)

	return err
}

type NullableGatewayResponse struct {
	value *GatewayResponse
	isSet bool
}

func (v NullableGatewayResponse) Get() *GatewayResponse {
	return v.value
}

func (v *NullableGatewayResponse) Set(val *GatewayResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayResponse(val *GatewayResponse) *NullableGatewayResponse {
	return &NullableGatewayResponse{value: val, isSet: true}
}

func (v NullableGatewayResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


