/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MessageMoveResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageMoveResponse{}

// MessageMoveResponse struct for MessageMoveResponse
type MessageMoveResponse struct {
	// ID of the moved message. Only included if the server provides it.
	Id *string `json:"id,omitempty"`
	// Destination mailbox folder path
	Path string `json:"path"`
	// UID of the moved message, applies only to IMAP accounts. Only included if the server provides it.
	Uid *int32 `json:"uid,omitempty"`
}

type _MessageMoveResponse MessageMoveResponse

// NewMessageMoveResponse instantiates a new MessageMoveResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageMoveResponse(path string) *MessageMoveResponse {
	this := MessageMoveResponse{}
	this.Path = path
	return &this
}

// NewMessageMoveResponseWithDefaults instantiates a new MessageMoveResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageMoveResponseWithDefaults() *MessageMoveResponse {
	this := MessageMoveResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *MessageMoveResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageMoveResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *MessageMoveResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *MessageMoveResponse) SetId(v string) {
	o.Id = &v
}

// GetPath returns the Path field value
func (o *MessageMoveResponse) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *MessageMoveResponse) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *MessageMoveResponse) SetPath(v string) {
	o.Path = v
}

// GetUid returns the Uid field value if set, zero value otherwise.
func (o *MessageMoveResponse) GetUid() int32 {
	if o == nil || IsNil(o.Uid) {
		var ret int32
		return ret
	}
	return *o.Uid
}

// GetUidOk returns a tuple with the Uid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageMoveResponse) GetUidOk() (*int32, bool) {
	if o == nil || IsNil(o.Uid) {
		return nil, false
	}
	return o.Uid, true
}

// HasUid returns a boolean if a field has been set.
func (o *MessageMoveResponse) HasUid() bool {
	if o != nil && !IsNil(o.Uid) {
		return true
	}

	return false
}

// SetUid gets a reference to the given int32 and assigns it to the Uid field.
func (o *MessageMoveResponse) SetUid(v int32) {
	o.Uid = &v
}

func (o MessageMoveResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageMoveResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["path"] = o.Path
	if !IsNil(o.Uid) {
		toSerialize["uid"] = o.Uid
	}
	return toSerialize, nil
}

func (o *MessageMoveResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"path",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMessageMoveResponse := _MessageMoveResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMessageMoveResponse)

	if err != nil {
		return err
	}

	*o = MessageMoveResponse(varMessageMoveResponse)

	return err
}

type NullableMessageMoveResponse struct {
	value *MessageMoveResponse
	isSet bool
}

func (v NullableMessageMoveResponse) Get() *MessageMoveResponse {
	return v.value
}

func (v *NullableMessageMoveResponse) Set(val *MessageMoveResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageMoveResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageMoveResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageMoveResponse(val *MessageMoveResponse) *NullableMessageMoveResponse {
	return &NullableMessageMoveResponse{value: val, isSet: true}
}

func (v NullableMessageMoveResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageMoveResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


