/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the CreateMailbox type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateMailbox{}

// CreateMailbox struct for CreateMailbox
type CreateMailbox struct {
	// Mailbox path as an array or a string. If account is namespaced then namespace prefix is added by default.
	Path []string `json:"path,omitempty"`
}

// NewCreateMailbox instantiates a new CreateMailbox object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateMailbox() *CreateMailbox {
	this := CreateMailbox{}
	return &this
}

// NewCreateMailboxWithDefaults instantiates a new CreateMailbox object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateMailboxWithDefaults() *CreateMailbox {
	this := CreateMailbox{}
	return &this
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *CreateMailbox) GetPath() []string {
	if o == nil || IsNil(o.Path) {
		var ret []string
		return ret
	}
	return o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateMailbox) GetPathOk() ([]string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *CreateMailbox) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given []string and assigns it to the Path field.
func (o *CreateMailbox) SetPath(v []string) {
	o.Path = v
}

func (o CreateMailbox) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateMailbox) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	return toSerialize, nil
}

type NullableCreateMailbox struct {
	value *CreateMailbox
	isSet bool
}

func (v NullableCreateMailbox) Get() *CreateMailbox {
	return v.value
}

func (v *NullableCreateMailbox) Set(val *CreateMailbox) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateMailbox) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateMailbox) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateMailbox(val *CreateMailbox) *NullableCreateMailbox {
	return &NullableCreateMailbox{value: val, isSet: true}
}

func (v NullableCreateMailbox) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateMailbox) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


