/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the AccountCounters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountCounters{}

// AccountCounters struct for AccountCounters
type AccountCounters struct {
	// Cumulative event counters for the account lifetime
	Events map[string]interface{} `json:"events,omitempty"`
}

// NewAccountCounters instantiates a new AccountCounters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountCounters() *AccountCounters {
	this := AccountCounters{}
	return &this
}

// NewAccountCountersWithDefaults instantiates a new AccountCounters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountCountersWithDefaults() *AccountCounters {
	this := AccountCounters{}
	return &this
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *AccountCounters) GetEvents() map[string]interface{} {
	if o == nil || IsNil(o.Events) {
		var ret map[string]interface{}
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountCounters) GetEventsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Events) {
		return map[string]interface{}{}, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *AccountCounters) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given map[string]interface{} and assigns it to the Events field.
func (o *AccountCounters) SetEvents(v map[string]interface{}) {
	o.Events = v
}

func (o AccountCounters) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountCounters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	return toSerialize, nil
}

type NullableAccountCounters struct {
	value *AccountCounters
	isSet bool
}

func (v NullableAccountCounters) Get() *AccountCounters {
	return v.value
}

func (v *NullableAccountCounters) Set(val *AccountCounters) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountCounters) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountCounters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountCounters(val *AccountCounters) *NullableAccountCounters {
	return &NullableAccountCounters{value: val, isSet: true}
}

func (v NullableAccountCounters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountCounters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


