/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// IMAPIndexer Override global IMAP indexing strategy for this account. \"full\" tracks all changes including deletions, \"fast\" only detects new messages.
type IMAPIndexer string

// List of IMAPIndexer
const (
	IMAPINDEXER_FULL IMAPIndexer = "full"
	IMAPINDEXER_FAST IMAPIndexer = "fast"
)

// All allowed values of IMAPIndexer enum
var AllowedIMAPIndexerEnumValues = []IMAPIndexer{
	"full",
	"fast",
}

func (v *IMAPIndexer) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := IMAPIndexer(value)
	for _, existing := range AllowedIMAPIndexerEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid IMAPIndexer", value)
}

// NewIMAPIndexerFromValue returns a pointer to a valid IMAPIndexer
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewIMAPIndexerFromValue(v string) (*IMAPIndexer, error) {
	ev := IMAPIndexer(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for IMAPIndexer: valid values are %v", v, AllowedIMAPIndexerEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v IMAPIndexer) IsValid() bool {
	for _, existing := range AllowedIMAPIndexerEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to IMAPIndexer value
func (v IMAPIndexer) Ptr() *IMAPIndexer {
	return &v
}

type NullableIMAPIndexer struct {
	value *IMAPIndexer
	isSet bool
}

func (v NullableIMAPIndexer) Get() *IMAPIndexer {
	return v.value
}

func (v *NullableIMAPIndexer) Set(val *IMAPIndexer) {
	v.value = val
	v.isSet = true
}

func (v NullableIMAPIndexer) IsSet() bool {
	return v.isSet
}

func (v *NullableIMAPIndexer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIMAPIndexer(val *IMAPIndexer) *NullableIMAPIndexer {
	return &NullableIMAPIndexer{value: val, isSet: true}
}

func (v NullableIMAPIndexer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIMAPIndexer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

