/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegisterLicense type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterLicense{}

// RegisterLicense struct for RegisterLicense
type RegisterLicense struct {
	// License file
	License string `json:"license"`
}

type _RegisterLicense RegisterLicense

// NewRegisterLicense instantiates a new RegisterLicense object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterLicense(license string) *RegisterLicense {
	this := RegisterLicense{}
	this.License = license
	return &this
}

// NewRegisterLicenseWithDefaults instantiates a new RegisterLicense object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterLicenseWithDefaults() *RegisterLicense {
	this := RegisterLicense{}
	return &this
}

// GetLicense returns the License field value
func (o *RegisterLicense) GetLicense() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.License
}

// GetLicenseOk returns a tuple with the License field value
// and a boolean to check if the value has been set.
func (o *RegisterLicense) GetLicenseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.License, true
}

// SetLicense sets field value
func (o *RegisterLicense) SetLicense(v string) {
	o.License = v
}

func (o RegisterLicense) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterLicense) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["license"] = o.License
	return toSerialize, nil
}

func (o *RegisterLicense) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"license",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterLicense := _RegisterLicense{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegisterLicense)

	if err != nil {
		return err
	}

	*o = RegisterLicense(varRegisterLicense)

	return err
}

type NullableRegisterLicense struct {
	value *RegisterLicense
	isSet bool
}

func (v NullableRegisterLicense) Get() *RegisterLicense {
	return v.value
}

func (v *NullableRegisterLicense) Set(val *RegisterLicense) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterLicense) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterLicense) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterLicense(val *RegisterLicense) *NullableRegisterLicense {
	return &NullableRegisterLicense{value: val, isSet: true}
}

func (v NullableRegisterLicense) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterLicense) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


