/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateOAuthAppResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOAuthAppResponse{}

// UpdateOAuthAppResponse struct for UpdateOAuthAppResponse
type UpdateOAuthAppResponse struct {
	// OAuth2 app ID
	Id string `json:"id"`
}

type _UpdateOAuthAppResponse UpdateOAuthAppResponse

// NewUpdateOAuthAppResponse instantiates a new UpdateOAuthAppResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOAuthAppResponse(id string) *UpdateOAuthAppResponse {
	this := UpdateOAuthAppResponse{}
	this.Id = id
	return &this
}

// NewUpdateOAuthAppResponseWithDefaults instantiates a new UpdateOAuthAppResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOAuthAppResponseWithDefaults() *UpdateOAuthAppResponse {
	this := UpdateOAuthAppResponse{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateOAuthAppResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateOAuthAppResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateOAuthAppResponse) SetId(v string) {
	o.Id = v
}

func (o UpdateOAuthAppResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOAuthAppResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *UpdateOAuthAppResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateOAuthAppResponse := _UpdateOAuthAppResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateOAuthAppResponse)

	if err != nil {
		return err
	}

	*o = UpdateOAuthAppResponse(varUpdateOAuthAppResponse)

	return err
}

type NullableUpdateOAuthAppResponse struct {
	value *UpdateOAuthAppResponse
	isSet bool
}

func (v NullableUpdateOAuthAppResponse) Get() *UpdateOAuthAppResponse {
	return v.value
}

func (v *NullableUpdateOAuthAppResponse) Set(val *UpdateOAuthAppResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOAuthAppResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOAuthAppResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOAuthAppResponse(val *UpdateOAuthAppResponse) *NullableUpdateOAuthAppResponse {
	return &NullableUpdateOAuthAppResponse{value: val, isSet: true}
}

func (v NullableUpdateOAuthAppResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOAuthAppResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


