/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the DiscoveredEmailSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DiscoveredEmailSettings{}

// DiscoveredEmailSettings struct for DiscoveredEmailSettings
type DiscoveredEmailSettings struct {
	// Source for the detected info
	Source *string `json:"_source,omitempty"`
	Imap *ResolvedServerSettings `json:"imap,omitempty"`
	Smtp *DiscoveredServerSettings `json:"smtp,omitempty"`
}

// NewDiscoveredEmailSettings instantiates a new DiscoveredEmailSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDiscoveredEmailSettings() *DiscoveredEmailSettings {
	this := DiscoveredEmailSettings{}
	return &this
}

// NewDiscoveredEmailSettingsWithDefaults instantiates a new DiscoveredEmailSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiscoveredEmailSettingsWithDefaults() *DiscoveredEmailSettings {
	this := DiscoveredEmailSettings{}
	return &this
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *DiscoveredEmailSettings) GetSource() string {
	if o == nil || IsNil(o.Source) {
		var ret string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiscoveredEmailSettings) GetSourceOk() (*string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *DiscoveredEmailSettings) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given string and assigns it to the Source field.
func (o *DiscoveredEmailSettings) SetSource(v string) {
	o.Source = &v
}

// GetImap returns the Imap field value if set, zero value otherwise.
func (o *DiscoveredEmailSettings) GetImap() ResolvedServerSettings {
	if o == nil || IsNil(o.Imap) {
		var ret ResolvedServerSettings
		return ret
	}
	return *o.Imap
}

// GetImapOk returns a tuple with the Imap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiscoveredEmailSettings) GetImapOk() (*ResolvedServerSettings, bool) {
	if o == nil || IsNil(o.Imap) {
		return nil, false
	}
	return o.Imap, true
}

// HasImap returns a boolean if a field has been set.
func (o *DiscoveredEmailSettings) HasImap() bool {
	if o != nil && !IsNil(o.Imap) {
		return true
	}

	return false
}

// SetImap gets a reference to the given ResolvedServerSettings and assigns it to the Imap field.
func (o *DiscoveredEmailSettings) SetImap(v ResolvedServerSettings) {
	o.Imap = &v
}

// GetSmtp returns the Smtp field value if set, zero value otherwise.
func (o *DiscoveredEmailSettings) GetSmtp() DiscoveredServerSettings {
	if o == nil || IsNil(o.Smtp) {
		var ret DiscoveredServerSettings
		return ret
	}
	return *o.Smtp
}

// GetSmtpOk returns a tuple with the Smtp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiscoveredEmailSettings) GetSmtpOk() (*DiscoveredServerSettings, bool) {
	if o == nil || IsNil(o.Smtp) {
		return nil, false
	}
	return o.Smtp, true
}

// HasSmtp returns a boolean if a field has been set.
func (o *DiscoveredEmailSettings) HasSmtp() bool {
	if o != nil && !IsNil(o.Smtp) {
		return true
	}

	return false
}

// SetSmtp gets a reference to the given DiscoveredServerSettings and assigns it to the Smtp field.
func (o *DiscoveredEmailSettings) SetSmtp(v DiscoveredServerSettings) {
	o.Smtp = &v
}

func (o DiscoveredEmailSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DiscoveredEmailSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Source) {
		toSerialize["_source"] = o.Source
	}
	if !IsNil(o.Imap) {
		toSerialize["imap"] = o.Imap
	}
	if !IsNil(o.Smtp) {
		toSerialize["smtp"] = o.Smtp
	}
	return toSerialize, nil
}

type NullableDiscoveredEmailSettings struct {
	value *DiscoveredEmailSettings
	isSet bool
}

func (v NullableDiscoveredEmailSettings) Get() *DiscoveredEmailSettings {
	return v.value
}

func (v *NullableDiscoveredEmailSettings) Set(val *DiscoveredEmailSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableDiscoveredEmailSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableDiscoveredEmailSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiscoveredEmailSettings(val *DiscoveredEmailSettings) *NullableDiscoveredEmailSettings {
	return &NullableDiscoveredEmailSettings{value: val, isSet: true}
}

func (v NullableDiscoveredEmailSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiscoveredEmailSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


