/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the WebhookRouteContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookRouteContent{}

// WebhookRouteContent struct for WebhookRouteContent
type WebhookRouteContent struct {
	// Filter function
	Fn *string `json:"fn,omitempty"`
	// Mapping function
	Map *string `json:"map,omitempty"`
}

// NewWebhookRouteContent instantiates a new WebhookRouteContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookRouteContent() *WebhookRouteContent {
	this := WebhookRouteContent{}
	return &this
}

// NewWebhookRouteContentWithDefaults instantiates a new WebhookRouteContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookRouteContentWithDefaults() *WebhookRouteContent {
	this := WebhookRouteContent{}
	return &this
}

// GetFn returns the Fn field value if set, zero value otherwise.
func (o *WebhookRouteContent) GetFn() string {
	if o == nil || IsNil(o.Fn) {
		var ret string
		return ret
	}
	return *o.Fn
}

// GetFnOk returns a tuple with the Fn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookRouteContent) GetFnOk() (*string, bool) {
	if o == nil || IsNil(o.Fn) {
		return nil, false
	}
	return o.Fn, true
}

// HasFn returns a boolean if a field has been set.
func (o *WebhookRouteContent) HasFn() bool {
	if o != nil && !IsNil(o.Fn) {
		return true
	}

	return false
}

// SetFn gets a reference to the given string and assigns it to the Fn field.
func (o *WebhookRouteContent) SetFn(v string) {
	o.Fn = &v
}

// GetMap returns the Map field value if set, zero value otherwise.
func (o *WebhookRouteContent) GetMap() string {
	if o == nil || IsNil(o.Map) {
		var ret string
		return ret
	}
	return *o.Map
}

// GetMapOk returns a tuple with the Map field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookRouteContent) GetMapOk() (*string, bool) {
	if o == nil || IsNil(o.Map) {
		return nil, false
	}
	return o.Map, true
}

// HasMap returns a boolean if a field has been set.
func (o *WebhookRouteContent) HasMap() bool {
	if o != nil && !IsNil(o.Map) {
		return true
	}

	return false
}

// SetMap gets a reference to the given string and assigns it to the Map field.
func (o *WebhookRouteContent) SetMap(v string) {
	o.Map = &v
}

func (o WebhookRouteContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookRouteContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Fn) {
		toSerialize["fn"] = o.Fn
	}
	if !IsNil(o.Map) {
		toSerialize["map"] = o.Map
	}
	return toSerialize, nil
}

type NullableWebhookRouteContent struct {
	value *WebhookRouteContent
	isSet bool
}

func (v NullableWebhookRouteContent) Get() *WebhookRouteContent {
	return v.value
}

func (v *NullableWebhookRouteContent) Set(val *WebhookRouteContent) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookRouteContent) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookRouteContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookRouteContent(val *WebhookRouteContent) *NullableWebhookRouteContent {
	return &NullableWebhookRouteContent{value: val, isSet: true}
}

func (v NullableWebhookRouteContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookRouteContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


