/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// ServiceClient Service client ID for 2-legged OAuth2 applications
type ServiceClient string

// List of serviceClient
const (
	SERVICECLIENT_FALSE ServiceClient = "false"
)

// All allowed values of ServiceClient enum
var AllowedServiceClientEnumValues = []ServiceClient{
	"false",
}

func (v *ServiceClient) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := ServiceClient(value)
	for _, existing := range AllowedServiceClientEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid ServiceClient", value)
}

// NewServiceClientFromValue returns a pointer to a valid ServiceClient
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewServiceClientFromValue(v string) (*ServiceClient, error) {
	ev := ServiceClient(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ServiceClient: valid values are %v", v, AllowedServiceClientEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ServiceClient) IsValid() bool {
	for _, existing := range AllowedServiceClientEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to serviceClient value
func (v ServiceClient) Ptr() *ServiceClient {
	return &v
}

type NullableServiceClient struct {
	value *ServiceClient
	isSet bool
}

func (v NullableServiceClient) Get() *ServiceClient {
	return v.value
}

func (v *NullableServiceClient) Set(val *ServiceClient) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceClient) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceClient) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceClient(val *ServiceClient) *NullableServiceClient {
	return &NullableServiceClient{value: val, isSet: true}
}

func (v NullableServiceClient) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceClient) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

