/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the MailboxesFilterResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailboxesFilterResponse{}

// MailboxesFilterResponse struct for MailboxesFilterResponse
type MailboxesFilterResponse struct {
	Mailboxes []MailboxResponseItem `json:"mailboxes,omitempty"`
}

// NewMailboxesFilterResponse instantiates a new MailboxesFilterResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailboxesFilterResponse() *MailboxesFilterResponse {
	this := MailboxesFilterResponse{}
	return &this
}

// NewMailboxesFilterResponseWithDefaults instantiates a new MailboxesFilterResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailboxesFilterResponseWithDefaults() *MailboxesFilterResponse {
	this := MailboxesFilterResponse{}
	return &this
}

// GetMailboxes returns the Mailboxes field value if set, zero value otherwise.
func (o *MailboxesFilterResponse) GetMailboxes() []MailboxResponseItem {
	if o == nil || IsNil(o.Mailboxes) {
		var ret []MailboxResponseItem
		return ret
	}
	return o.Mailboxes
}

// GetMailboxesOk returns a tuple with the Mailboxes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MailboxesFilterResponse) GetMailboxesOk() ([]MailboxResponseItem, bool) {
	if o == nil || IsNil(o.Mailboxes) {
		return nil, false
	}
	return o.Mailboxes, true
}

// HasMailboxes returns a boolean if a field has been set.
func (o *MailboxesFilterResponse) HasMailboxes() bool {
	if o != nil && !IsNil(o.Mailboxes) {
		return true
	}

	return false
}

// SetMailboxes gets a reference to the given []MailboxResponseItem and assigns it to the Mailboxes field.
func (o *MailboxesFilterResponse) SetMailboxes(v []MailboxResponseItem) {
	o.Mailboxes = v
}

func (o MailboxesFilterResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailboxesFilterResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Mailboxes) {
		toSerialize["mailboxes"] = o.Mailboxes
	}
	return toSerialize, nil
}

type NullableMailboxesFilterResponse struct {
	value *MailboxesFilterResponse
	isSet bool
}

func (v NullableMailboxesFilterResponse) Get() *MailboxesFilterResponse {
	return v.value
}

func (v *NullableMailboxesFilterResponse) Set(val *MailboxesFilterResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMailboxesFilterResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMailboxesFilterResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailboxesFilterResponse(val *MailboxesFilterResponse) *NullableMailboxesFilterResponse {
	return &NullableMailboxesFilterResponse{value: val, isSet: true}
}

func (v NullableMailboxesFilterResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailboxesFilterResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


