/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the IMAPUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IMAPUpdate{}

// IMAPUpdate IMAP configuration
type IMAPUpdate struct {
	// Custom folder path for archived messages. Set to null to use default.
	ArchiveMailPath NullableString `json:"archiveMailPath,omitempty"`
	Auth *Authentication `json:"auth,omitempty"`
	// Temporarily disable IMAP operations for this account
	Disabled *bool `json:"disabled,omitempty"`
	// Custom folder path for draft messages. Set to null to use default.
	DraftsMailPath NullableString `json:"draftsMailPath,omitempty"`
	// IMAP server hostname
	Host *string `json:"host,omitempty"`
	// Custom folder path for spam/junk messages. Set to null to use default.
	JunkMailPath NullableString `json:"junkMailPath,omitempty"`
	// Update only the provided fields instead of replacing the entire configuration
	Partial *bool `json:"partial,omitempty"`
	// IMAP server port
	Port *int32 `json:"port,omitempty"`
	// Delay in seconds between full mailbox resynchronizations
	ResyncDelay *int32 `json:"resyncDelay,omitempty"`
	// Use TLS encryption for the connection
	Secure *bool `json:"secure,omitempty"`
	// Custom folder path for sent messages. Set to null to use default.
	SentMailPath NullableString `json:"sentMailPath,omitempty"`
	Tls *Model15 `json:"tls,omitempty"`
	// Custom folder path for deleted messages. Set to null to use default.
	TrashMailPath NullableString `json:"trashMailPath,omitempty"`
	// Use external authentication server to retrieve credentials dynamically
	UseAuthServer *bool `json:"useAuthServer,omitempty"`
}

// NewIMAPUpdate instantiates a new IMAPUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIMAPUpdate() *IMAPUpdate {
	this := IMAPUpdate{}
	var partial bool = false
	this.Partial = &partial
	return &this
}

// NewIMAPUpdateWithDefaults instantiates a new IMAPUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIMAPUpdateWithDefaults() *IMAPUpdate {
	this := IMAPUpdate{}
	var partial bool = false
	this.Partial = &partial
	return &this
}

// GetArchiveMailPath returns the ArchiveMailPath field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IMAPUpdate) GetArchiveMailPath() string {
	if o == nil || IsNil(o.ArchiveMailPath.Get()) {
		var ret string
		return ret
	}
	return *o.ArchiveMailPath.Get()
}

// GetArchiveMailPathOk returns a tuple with the ArchiveMailPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IMAPUpdate) GetArchiveMailPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ArchiveMailPath.Get(), o.ArchiveMailPath.IsSet()
}

// HasArchiveMailPath returns a boolean if a field has been set.
func (o *IMAPUpdate) HasArchiveMailPath() bool {
	if o != nil && o.ArchiveMailPath.IsSet() {
		return true
	}

	return false
}

// SetArchiveMailPath gets a reference to the given NullableString and assigns it to the ArchiveMailPath field.
func (o *IMAPUpdate) SetArchiveMailPath(v string) {
	o.ArchiveMailPath.Set(&v)
}
// SetArchiveMailPathNil sets the value for ArchiveMailPath to be an explicit nil
func (o *IMAPUpdate) SetArchiveMailPathNil() {
	o.ArchiveMailPath.Set(nil)
}

// UnsetArchiveMailPath ensures that no value is present for ArchiveMailPath, not even an explicit nil
func (o *IMAPUpdate) UnsetArchiveMailPath() {
	o.ArchiveMailPath.Unset()
}

// GetAuth returns the Auth field value if set, zero value otherwise.
func (o *IMAPUpdate) GetAuth() Authentication {
	if o == nil || IsNil(o.Auth) {
		var ret Authentication
		return ret
	}
	return *o.Auth
}

// GetAuthOk returns a tuple with the Auth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IMAPUpdate) GetAuthOk() (*Authentication, bool) {
	if o == nil || IsNil(o.Auth) {
		return nil, false
	}
	return o.Auth, true
}

// HasAuth returns a boolean if a field has been set.
func (o *IMAPUpdate) HasAuth() bool {
	if o != nil && !IsNil(o.Auth) {
		return true
	}

	return false
}

// SetAuth gets a reference to the given Authentication and assigns it to the Auth field.
func (o *IMAPUpdate) SetAuth(v Authentication) {
	o.Auth = &v
}

// GetDisabled returns the Disabled field value if set, zero value otherwise.
func (o *IMAPUpdate) GetDisabled() bool {
	if o == nil || IsNil(o.Disabled) {
		var ret bool
		return ret
	}
	return *o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IMAPUpdate) GetDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Disabled) {
		return nil, false
	}
	return o.Disabled, true
}

// HasDisabled returns a boolean if a field has been set.
func (o *IMAPUpdate) HasDisabled() bool {
	if o != nil && !IsNil(o.Disabled) {
		return true
	}

	return false
}

// SetDisabled gets a reference to the given bool and assigns it to the Disabled field.
func (o *IMAPUpdate) SetDisabled(v bool) {
	o.Disabled = &v
}

// GetDraftsMailPath returns the DraftsMailPath field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IMAPUpdate) GetDraftsMailPath() string {
	if o == nil || IsNil(o.DraftsMailPath.Get()) {
		var ret string
		return ret
	}
	return *o.DraftsMailPath.Get()
}

// GetDraftsMailPathOk returns a tuple with the DraftsMailPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IMAPUpdate) GetDraftsMailPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DraftsMailPath.Get(), o.DraftsMailPath.IsSet()
}

// HasDraftsMailPath returns a boolean if a field has been set.
func (o *IMAPUpdate) HasDraftsMailPath() bool {
	if o != nil && o.DraftsMailPath.IsSet() {
		return true
	}

	return false
}

// SetDraftsMailPath gets a reference to the given NullableString and assigns it to the DraftsMailPath field.
func (o *IMAPUpdate) SetDraftsMailPath(v string) {
	o.DraftsMailPath.Set(&v)
}
// SetDraftsMailPathNil sets the value for DraftsMailPath to be an explicit nil
func (o *IMAPUpdate) SetDraftsMailPathNil() {
	o.DraftsMailPath.Set(nil)
}

// UnsetDraftsMailPath ensures that no value is present for DraftsMailPath, not even an explicit nil
func (o *IMAPUpdate) UnsetDraftsMailPath() {
	o.DraftsMailPath.Unset()
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *IMAPUpdate) GetHost() string {
	if o == nil || IsNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IMAPUpdate) GetHostOk() (*string, bool) {
	if o == nil || IsNil(o.Host) {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *IMAPUpdate) HasHost() bool {
	if o != nil && !IsNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *IMAPUpdate) SetHost(v string) {
	o.Host = &v
}

// GetJunkMailPath returns the JunkMailPath field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IMAPUpdate) GetJunkMailPath() string {
	if o == nil || IsNil(o.JunkMailPath.Get()) {
		var ret string
		return ret
	}
	return *o.JunkMailPath.Get()
}

// GetJunkMailPathOk returns a tuple with the JunkMailPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IMAPUpdate) GetJunkMailPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.JunkMailPath.Get(), o.JunkMailPath.IsSet()
}

// HasJunkMailPath returns a boolean if a field has been set.
func (o *IMAPUpdate) HasJunkMailPath() bool {
	if o != nil && o.JunkMailPath.IsSet() {
		return true
	}

	return false
}

// SetJunkMailPath gets a reference to the given NullableString and assigns it to the JunkMailPath field.
func (o *IMAPUpdate) SetJunkMailPath(v string) {
	o.JunkMailPath.Set(&v)
}
// SetJunkMailPathNil sets the value for JunkMailPath to be an explicit nil
func (o *IMAPUpdate) SetJunkMailPathNil() {
	o.JunkMailPath.Set(nil)
}

// UnsetJunkMailPath ensures that no value is present for JunkMailPath, not even an explicit nil
func (o *IMAPUpdate) UnsetJunkMailPath() {
	o.JunkMailPath.Unset()
}

// GetPartial returns the Partial field value if set, zero value otherwise.
func (o *IMAPUpdate) GetPartial() bool {
	if o == nil || IsNil(o.Partial) {
		var ret bool
		return ret
	}
	return *o.Partial
}

// GetPartialOk returns a tuple with the Partial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IMAPUpdate) GetPartialOk() (*bool, bool) {
	if o == nil || IsNil(o.Partial) {
		return nil, false
	}
	return o.Partial, true
}

// HasPartial returns a boolean if a field has been set.
func (o *IMAPUpdate) HasPartial() bool {
	if o != nil && !IsNil(o.Partial) {
		return true
	}

	return false
}

// SetPartial gets a reference to the given bool and assigns it to the Partial field.
func (o *IMAPUpdate) SetPartial(v bool) {
	o.Partial = &v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *IMAPUpdate) GetPort() int32 {
	if o == nil || IsNil(o.Port) {
		var ret int32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IMAPUpdate) GetPortOk() (*int32, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *IMAPUpdate) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given int32 and assigns it to the Port field.
func (o *IMAPUpdate) SetPort(v int32) {
	o.Port = &v
}

// GetResyncDelay returns the ResyncDelay field value if set, zero value otherwise.
func (o *IMAPUpdate) GetResyncDelay() int32 {
	if o == nil || IsNil(o.ResyncDelay) {
		var ret int32
		return ret
	}
	return *o.ResyncDelay
}

// GetResyncDelayOk returns a tuple with the ResyncDelay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IMAPUpdate) GetResyncDelayOk() (*int32, bool) {
	if o == nil || IsNil(o.ResyncDelay) {
		return nil, false
	}
	return o.ResyncDelay, true
}

// HasResyncDelay returns a boolean if a field has been set.
func (o *IMAPUpdate) HasResyncDelay() bool {
	if o != nil && !IsNil(o.ResyncDelay) {
		return true
	}

	return false
}

// SetResyncDelay gets a reference to the given int32 and assigns it to the ResyncDelay field.
func (o *IMAPUpdate) SetResyncDelay(v int32) {
	o.ResyncDelay = &v
}

// GetSecure returns the Secure field value if set, zero value otherwise.
func (o *IMAPUpdate) GetSecure() bool {
	if o == nil || IsNil(o.Secure) {
		var ret bool
		return ret
	}
	return *o.Secure
}

// GetSecureOk returns a tuple with the Secure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IMAPUpdate) GetSecureOk() (*bool, bool) {
	if o == nil || IsNil(o.Secure) {
		return nil, false
	}
	return o.Secure, true
}

// HasSecure returns a boolean if a field has been set.
func (o *IMAPUpdate) HasSecure() bool {
	if o != nil && !IsNil(o.Secure) {
		return true
	}

	return false
}

// SetSecure gets a reference to the given bool and assigns it to the Secure field.
func (o *IMAPUpdate) SetSecure(v bool) {
	o.Secure = &v
}

// GetSentMailPath returns the SentMailPath field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IMAPUpdate) GetSentMailPath() string {
	if o == nil || IsNil(o.SentMailPath.Get()) {
		var ret string
		return ret
	}
	return *o.SentMailPath.Get()
}

// GetSentMailPathOk returns a tuple with the SentMailPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IMAPUpdate) GetSentMailPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SentMailPath.Get(), o.SentMailPath.IsSet()
}

// HasSentMailPath returns a boolean if a field has been set.
func (o *IMAPUpdate) HasSentMailPath() bool {
	if o != nil && o.SentMailPath.IsSet() {
		return true
	}

	return false
}

// SetSentMailPath gets a reference to the given NullableString and assigns it to the SentMailPath field.
func (o *IMAPUpdate) SetSentMailPath(v string) {
	o.SentMailPath.Set(&v)
}
// SetSentMailPathNil sets the value for SentMailPath to be an explicit nil
func (o *IMAPUpdate) SetSentMailPathNil() {
	o.SentMailPath.Set(nil)
}

// UnsetSentMailPath ensures that no value is present for SentMailPath, not even an explicit nil
func (o *IMAPUpdate) UnsetSentMailPath() {
	o.SentMailPath.Unset()
}

// GetTls returns the Tls field value if set, zero value otherwise.
func (o *IMAPUpdate) GetTls() Model15 {
	if o == nil || IsNil(o.Tls) {
		var ret Model15
		return ret
	}
	return *o.Tls
}

// GetTlsOk returns a tuple with the Tls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IMAPUpdate) GetTlsOk() (*Model15, bool) {
	if o == nil || IsNil(o.Tls) {
		return nil, false
	}
	return o.Tls, true
}

// HasTls returns a boolean if a field has been set.
func (o *IMAPUpdate) HasTls() bool {
	if o != nil && !IsNil(o.Tls) {
		return true
	}

	return false
}

// SetTls gets a reference to the given Model15 and assigns it to the Tls field.
func (o *IMAPUpdate) SetTls(v Model15) {
	o.Tls = &v
}

// GetTrashMailPath returns the TrashMailPath field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *IMAPUpdate) GetTrashMailPath() string {
	if o == nil || IsNil(o.TrashMailPath.Get()) {
		var ret string
		return ret
	}
	return *o.TrashMailPath.Get()
}

// GetTrashMailPathOk returns a tuple with the TrashMailPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *IMAPUpdate) GetTrashMailPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TrashMailPath.Get(), o.TrashMailPath.IsSet()
}

// HasTrashMailPath returns a boolean if a field has been set.
func (o *IMAPUpdate) HasTrashMailPath() bool {
	if o != nil && o.TrashMailPath.IsSet() {
		return true
	}

	return false
}

// SetTrashMailPath gets a reference to the given NullableString and assigns it to the TrashMailPath field.
func (o *IMAPUpdate) SetTrashMailPath(v string) {
	o.TrashMailPath.Set(&v)
}
// SetTrashMailPathNil sets the value for TrashMailPath to be an explicit nil
func (o *IMAPUpdate) SetTrashMailPathNil() {
	o.TrashMailPath.Set(nil)
}

// UnsetTrashMailPath ensures that no value is present for TrashMailPath, not even an explicit nil
func (o *IMAPUpdate) UnsetTrashMailPath() {
	o.TrashMailPath.Unset()
}

// GetUseAuthServer returns the UseAuthServer field value if set, zero value otherwise.
func (o *IMAPUpdate) GetUseAuthServer() bool {
	if o == nil || IsNil(o.UseAuthServer) {
		var ret bool
		return ret
	}
	return *o.UseAuthServer
}

// GetUseAuthServerOk returns a tuple with the UseAuthServer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IMAPUpdate) GetUseAuthServerOk() (*bool, bool) {
	if o == nil || IsNil(o.UseAuthServer) {
		return nil, false
	}
	return o.UseAuthServer, true
}

// HasUseAuthServer returns a boolean if a field has been set.
func (o *IMAPUpdate) HasUseAuthServer() bool {
	if o != nil && !IsNil(o.UseAuthServer) {
		return true
	}

	return false
}

// SetUseAuthServer gets a reference to the given bool and assigns it to the UseAuthServer field.
func (o *IMAPUpdate) SetUseAuthServer(v bool) {
	o.UseAuthServer = &v
}

func (o IMAPUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IMAPUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ArchiveMailPath.IsSet() {
		toSerialize["archiveMailPath"] = o.ArchiveMailPath.Get()
	}
	if !IsNil(o.Auth) {
		toSerialize["auth"] = o.Auth
	}
	if !IsNil(o.Disabled) {
		toSerialize["disabled"] = o.Disabled
	}
	if o.DraftsMailPath.IsSet() {
		toSerialize["draftsMailPath"] = o.DraftsMailPath.Get()
	}
	if !IsNil(o.Host) {
		toSerialize["host"] = o.Host
	}
	if o.JunkMailPath.IsSet() {
		toSerialize["junkMailPath"] = o.JunkMailPath.Get()
	}
	if !IsNil(o.Partial) {
		toSerialize["partial"] = o.Partial
	}
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	if !IsNil(o.ResyncDelay) {
		toSerialize["resyncDelay"] = o.ResyncDelay
	}
	if !IsNil(o.Secure) {
		toSerialize["secure"] = o.Secure
	}
	if o.SentMailPath.IsSet() {
		toSerialize["sentMailPath"] = o.SentMailPath.Get()
	}
	if !IsNil(o.Tls) {
		toSerialize["tls"] = o.Tls
	}
	if o.TrashMailPath.IsSet() {
		toSerialize["trashMailPath"] = o.TrashMailPath.Get()
	}
	if !IsNil(o.UseAuthServer) {
		toSerialize["useAuthServer"] = o.UseAuthServer
	}
	return toSerialize, nil
}

type NullableIMAPUpdate struct {
	value *IMAPUpdate
	isSet bool
}

func (v NullableIMAPUpdate) Get() *IMAPUpdate {
	return v.value
}

func (v *NullableIMAPUpdate) Set(val *IMAPUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableIMAPUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableIMAPUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIMAPUpdate(val *IMAPUpdate) *NullableIMAPUpdate {
	return &NullableIMAPUpdate{value: val, isSet: true}
}

func (v NullableIMAPUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIMAPUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


