/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the UpdateTemplateContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateTemplateContent{}

// UpdateTemplateContent struct for UpdateTemplateContent
type UpdateTemplateContent struct {
	// HTML message content
	Html *string `json:"html,omitempty"`
	// Preview text shown in email clients after the subject line
	PreviewText *string `json:"previewText,omitempty"`
	// Email subject line
	Subject *string `json:"subject,omitempty"`
	// Plain text message content
	Text *string `json:"text,omitempty"`
}

// NewUpdateTemplateContent instantiates a new UpdateTemplateContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTemplateContent() *UpdateTemplateContent {
	this := UpdateTemplateContent{}
	return &this
}

// NewUpdateTemplateContentWithDefaults instantiates a new UpdateTemplateContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTemplateContentWithDefaults() *UpdateTemplateContent {
	this := UpdateTemplateContent{}
	return &this
}

// GetHtml returns the Html field value if set, zero value otherwise.
func (o *UpdateTemplateContent) GetHtml() string {
	if o == nil || IsNil(o.Html) {
		var ret string
		return ret
	}
	return *o.Html
}

// GetHtmlOk returns a tuple with the Html field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateContent) GetHtmlOk() (*string, bool) {
	if o == nil || IsNil(o.Html) {
		return nil, false
	}
	return o.Html, true
}

// HasHtml returns a boolean if a field has been set.
func (o *UpdateTemplateContent) HasHtml() bool {
	if o != nil && !IsNil(o.Html) {
		return true
	}

	return false
}

// SetHtml gets a reference to the given string and assigns it to the Html field.
func (o *UpdateTemplateContent) SetHtml(v string) {
	o.Html = &v
}

// GetPreviewText returns the PreviewText field value if set, zero value otherwise.
func (o *UpdateTemplateContent) GetPreviewText() string {
	if o == nil || IsNil(o.PreviewText) {
		var ret string
		return ret
	}
	return *o.PreviewText
}

// GetPreviewTextOk returns a tuple with the PreviewText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateContent) GetPreviewTextOk() (*string, bool) {
	if o == nil || IsNil(o.PreviewText) {
		return nil, false
	}
	return o.PreviewText, true
}

// HasPreviewText returns a boolean if a field has been set.
func (o *UpdateTemplateContent) HasPreviewText() bool {
	if o != nil && !IsNil(o.PreviewText) {
		return true
	}

	return false
}

// SetPreviewText gets a reference to the given string and assigns it to the PreviewText field.
func (o *UpdateTemplateContent) SetPreviewText(v string) {
	o.PreviewText = &v
}

// GetSubject returns the Subject field value if set, zero value otherwise.
func (o *UpdateTemplateContent) GetSubject() string {
	if o == nil || IsNil(o.Subject) {
		var ret string
		return ret
	}
	return *o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateContent) GetSubjectOk() (*string, bool) {
	if o == nil || IsNil(o.Subject) {
		return nil, false
	}
	return o.Subject, true
}

// HasSubject returns a boolean if a field has been set.
func (o *UpdateTemplateContent) HasSubject() bool {
	if o != nil && !IsNil(o.Subject) {
		return true
	}

	return false
}

// SetSubject gets a reference to the given string and assigns it to the Subject field.
func (o *UpdateTemplateContent) SetSubject(v string) {
	o.Subject = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *UpdateTemplateContent) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTemplateContent) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *UpdateTemplateContent) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *UpdateTemplateContent) SetText(v string) {
	o.Text = &v
}

func (o UpdateTemplateContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateTemplateContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Html) {
		toSerialize["html"] = o.Html
	}
	if !IsNil(o.PreviewText) {
		toSerialize["previewText"] = o.PreviewText
	}
	if !IsNil(o.Subject) {
		toSerialize["subject"] = o.Subject
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	return toSerialize, nil
}

type NullableUpdateTemplateContent struct {
	value *UpdateTemplateContent
	isSet bool
}

func (v NullableUpdateTemplateContent) Get() *UpdateTemplateContent {
	return v.value
}

func (v *NullableUpdateTemplateContent) Set(val *UpdateTemplateContent) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTemplateContent) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTemplateContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTemplateContent(val *UpdateTemplateContent) *NullableUpdateTemplateContent {
	return &NullableUpdateTemplateContent{value: val, isSet: true}
}

func (v NullableUpdateTemplateContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTemplateContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


