/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MessagesMoveRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessagesMoveRequest{}

// MessagesMoveRequest struct for MessagesMoveRequest
type MessagesMoveRequest struct {
	// Target mailbox folder path
	Path string `json:"path"`
	Search SearchQuery `json:"search"`
}

type _MessagesMoveRequest MessagesMoveRequest

// NewMessagesMoveRequest instantiates a new MessagesMoveRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessagesMoveRequest(path string, search SearchQuery) *MessagesMoveRequest {
	this := MessagesMoveRequest{}
	this.Path = path
	this.Search = search
	return &this
}

// NewMessagesMoveRequestWithDefaults instantiates a new MessagesMoveRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessagesMoveRequestWithDefaults() *MessagesMoveRequest {
	this := MessagesMoveRequest{}
	return &this
}

// GetPath returns the Path field value
func (o *MessagesMoveRequest) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *MessagesMoveRequest) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *MessagesMoveRequest) SetPath(v string) {
	o.Path = v
}

// GetSearch returns the Search field value
func (o *MessagesMoveRequest) GetSearch() SearchQuery {
	if o == nil {
		var ret SearchQuery
		return ret
	}

	return o.Search
}

// GetSearchOk returns a tuple with the Search field value
// and a boolean to check if the value has been set.
func (o *MessagesMoveRequest) GetSearchOk() (*SearchQuery, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Search, true
}

// SetSearch sets field value
func (o *MessagesMoveRequest) SetSearch(v SearchQuery) {
	o.Search = v
}

func (o MessagesMoveRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessagesMoveRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["path"] = o.Path
	toSerialize["search"] = o.Search
	return toSerialize, nil
}

func (o *MessagesMoveRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"path",
		"search",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMessagesMoveRequest := _MessagesMoveRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMessagesMoveRequest)

	if err != nil {
		return err
	}

	*o = MessagesMoveRequest(varMessagesMoveRequest)

	return err
}

type NullableMessagesMoveRequest struct {
	value *MessagesMoveRequest
	isSet bool
}

func (v NullableMessagesMoveRequest) Get() *MessagesMoveRequest {
	return v.value
}

func (v *NullableMessagesMoveRequest) Set(val *MessagesMoveRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMessagesMoveRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMessagesMoveRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessagesMoveRequest(val *MessagesMoveRequest) *NullableMessagesMoveRequest {
	return &NullableMessagesMoveRequest{value: val, isSet: true}
}

func (v NullableMessagesMoveRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessagesMoveRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


