/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the OAuth2Update type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OAuth2Update{}

// OAuth2Update OAuth2 configuration
type OAuth2Update struct {
	// OAuth2 access token for the email account
	AccessToken *string `json:"accessToken,omitempty"`
	Auth OAuth2Authentication `json:"auth"`
	// Request an OAuth2 authorization URL instead of directly configuring credentials
	Authorize *bool `json:"authorize,omitempty"`
	// Access token expiration timestamp
	Expires *time.Time `json:"expires,omitempty"`
	// Update only the provided fields instead of replacing the entire configuration
	Partial *bool `json:"partial,omitempty"`
	// OAuth2 Application ID configured in EmailEngine
	Provider *string `json:"provider,omitempty"`
	// OAuth2 refresh token for obtaining new access tokens
	RefreshToken *string `json:"refreshToken,omitempty"`
	// Use external authentication server for token management instead of EmailEngine
	UseAuthServer *bool `json:"useAuthServer,omitempty"`
}

type _OAuth2Update OAuth2Update

// NewOAuth2Update instantiates a new OAuth2Update object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOAuth2Update(auth OAuth2Authentication) *OAuth2Update {
	this := OAuth2Update{}
	this.Auth = auth
	var partial bool = false
	this.Partial = &partial
	return &this
}

// NewOAuth2UpdateWithDefaults instantiates a new OAuth2Update object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOAuth2UpdateWithDefaults() *OAuth2Update {
	this := OAuth2Update{}
	var partial bool = false
	this.Partial = &partial
	return &this
}

// GetAccessToken returns the AccessToken field value if set, zero value otherwise.
func (o *OAuth2Update) GetAccessToken() string {
	if o == nil || IsNil(o.AccessToken) {
		var ret string
		return ret
	}
	return *o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuth2Update) GetAccessTokenOk() (*string, bool) {
	if o == nil || IsNil(o.AccessToken) {
		return nil, false
	}
	return o.AccessToken, true
}

// HasAccessToken returns a boolean if a field has been set.
func (o *OAuth2Update) HasAccessToken() bool {
	if o != nil && !IsNil(o.AccessToken) {
		return true
	}

	return false
}

// SetAccessToken gets a reference to the given string and assigns it to the AccessToken field.
func (o *OAuth2Update) SetAccessToken(v string) {
	o.AccessToken = &v
}

// GetAuth returns the Auth field value
func (o *OAuth2Update) GetAuth() OAuth2Authentication {
	if o == nil {
		var ret OAuth2Authentication
		return ret
	}

	return o.Auth
}

// GetAuthOk returns a tuple with the Auth field value
// and a boolean to check if the value has been set.
func (o *OAuth2Update) GetAuthOk() (*OAuth2Authentication, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Auth, true
}

// SetAuth sets field value
func (o *OAuth2Update) SetAuth(v OAuth2Authentication) {
	o.Auth = v
}

// GetAuthorize returns the Authorize field value if set, zero value otherwise.
func (o *OAuth2Update) GetAuthorize() bool {
	if o == nil || IsNil(o.Authorize) {
		var ret bool
		return ret
	}
	return *o.Authorize
}

// GetAuthorizeOk returns a tuple with the Authorize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuth2Update) GetAuthorizeOk() (*bool, bool) {
	if o == nil || IsNil(o.Authorize) {
		return nil, false
	}
	return o.Authorize, true
}

// HasAuthorize returns a boolean if a field has been set.
func (o *OAuth2Update) HasAuthorize() bool {
	if o != nil && !IsNil(o.Authorize) {
		return true
	}

	return false
}

// SetAuthorize gets a reference to the given bool and assigns it to the Authorize field.
func (o *OAuth2Update) SetAuthorize(v bool) {
	o.Authorize = &v
}

// GetExpires returns the Expires field value if set, zero value otherwise.
func (o *OAuth2Update) GetExpires() time.Time {
	if o == nil || IsNil(o.Expires) {
		var ret time.Time
		return ret
	}
	return *o.Expires
}

// GetExpiresOk returns a tuple with the Expires field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuth2Update) GetExpiresOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Expires) {
		return nil, false
	}
	return o.Expires, true
}

// HasExpires returns a boolean if a field has been set.
func (o *OAuth2Update) HasExpires() bool {
	if o != nil && !IsNil(o.Expires) {
		return true
	}

	return false
}

// SetExpires gets a reference to the given time.Time and assigns it to the Expires field.
func (o *OAuth2Update) SetExpires(v time.Time) {
	o.Expires = &v
}

// GetPartial returns the Partial field value if set, zero value otherwise.
func (o *OAuth2Update) GetPartial() bool {
	if o == nil || IsNil(o.Partial) {
		var ret bool
		return ret
	}
	return *o.Partial
}

// GetPartialOk returns a tuple with the Partial field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuth2Update) GetPartialOk() (*bool, bool) {
	if o == nil || IsNil(o.Partial) {
		return nil, false
	}
	return o.Partial, true
}

// HasPartial returns a boolean if a field has been set.
func (o *OAuth2Update) HasPartial() bool {
	if o != nil && !IsNil(o.Partial) {
		return true
	}

	return false
}

// SetPartial gets a reference to the given bool and assigns it to the Partial field.
func (o *OAuth2Update) SetPartial(v bool) {
	o.Partial = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *OAuth2Update) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuth2Update) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *OAuth2Update) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *OAuth2Update) SetProvider(v string) {
	o.Provider = &v
}

// GetRefreshToken returns the RefreshToken field value if set, zero value otherwise.
func (o *OAuth2Update) GetRefreshToken() string {
	if o == nil || IsNil(o.RefreshToken) {
		var ret string
		return ret
	}
	return *o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuth2Update) GetRefreshTokenOk() (*string, bool) {
	if o == nil || IsNil(o.RefreshToken) {
		return nil, false
	}
	return o.RefreshToken, true
}

// HasRefreshToken returns a boolean if a field has been set.
func (o *OAuth2Update) HasRefreshToken() bool {
	if o != nil && !IsNil(o.RefreshToken) {
		return true
	}

	return false
}

// SetRefreshToken gets a reference to the given string and assigns it to the RefreshToken field.
func (o *OAuth2Update) SetRefreshToken(v string) {
	o.RefreshToken = &v
}

// GetUseAuthServer returns the UseAuthServer field value if set, zero value otherwise.
func (o *OAuth2Update) GetUseAuthServer() bool {
	if o == nil || IsNil(o.UseAuthServer) {
		var ret bool
		return ret
	}
	return *o.UseAuthServer
}

// GetUseAuthServerOk returns a tuple with the UseAuthServer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OAuth2Update) GetUseAuthServerOk() (*bool, bool) {
	if o == nil || IsNil(o.UseAuthServer) {
		return nil, false
	}
	return o.UseAuthServer, true
}

// HasUseAuthServer returns a boolean if a field has been set.
func (o *OAuth2Update) HasUseAuthServer() bool {
	if o != nil && !IsNil(o.UseAuthServer) {
		return true
	}

	return false
}

// SetUseAuthServer gets a reference to the given bool and assigns it to the UseAuthServer field.
func (o *OAuth2Update) SetUseAuthServer(v bool) {
	o.UseAuthServer = &v
}

func (o OAuth2Update) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OAuth2Update) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccessToken) {
		toSerialize["accessToken"] = o.AccessToken
	}
	toSerialize["auth"] = o.Auth
	if !IsNil(o.Authorize) {
		toSerialize["authorize"] = o.Authorize
	}
	if !IsNil(o.Expires) {
		toSerialize["expires"] = o.Expires
	}
	if !IsNil(o.Partial) {
		toSerialize["partial"] = o.Partial
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.RefreshToken) {
		toSerialize["refreshToken"] = o.RefreshToken
	}
	if !IsNil(o.UseAuthServer) {
		toSerialize["useAuthServer"] = o.UseAuthServer
	}
	return toSerialize, nil
}

func (o *OAuth2Update) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"auth",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOAuth2Update := _OAuth2Update{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOAuth2Update)

	if err != nil {
		return err
	}

	*o = OAuth2Update(varOAuth2Update)

	return err
}

type NullableOAuth2Update struct {
	value *OAuth2Update
	isSet bool
}

func (v NullableOAuth2Update) Get() *OAuth2Update {
	return v.value
}

func (v *NullableOAuth2Update) Set(val *OAuth2Update) {
	v.value = val
	v.isSet = true
}

func (v NullableOAuth2Update) IsSet() bool {
	return v.isSet
}

func (v *NullableOAuth2Update) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOAuth2Update(val *OAuth2Update) *NullableOAuth2Update {
	return &NullableOAuth2Update{value: val, isSet: true}
}

func (v NullableOAuth2Update) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOAuth2Update) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


