/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the Settings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Settings{}

// Settings struct for Settings
type Settings struct {
	// External authentication service URL for retrieving mailbox credentials dynamically
	AuthServer *string `json:"authServer,omitempty"`
	// Maximum number of delivery attempts before marking a message as permanently failed
	DeliveryAttempts *int32 `json:"deliveryAttempts,omitempty"`
	// Trust X-Forwarded-* headers when behind a reverse proxy
	EnableApiProxy *bool `json:"enableApiProxy,omitempty"`
	// Generate AI-powered summaries for incoming emails using OpenAI
	GenerateEmailSummary *bool `json:"generateEmailSummary,omitempty"`
	// Allow connections to mail servers with self-signed or invalid TLS certificates (not recommended for production)
	IgnoreMailCertErrors *bool `json:"ignoreMailCertErrors,omitempty"`
	// Client name advertised via IMAP ID extension
	ImapClientName *string `json:"imapClientName,omitempty"`
	// Support URL advertised via IMAP ID extension
	ImapClientSupportUrl *string `json:"imapClientSupportUrl,omitempty"`
	// Vendor name advertised via IMAP ID extension
	ImapClientVendor *string `json:"imapClientVendor,omitempty"`
	// Client version advertised via IMAP ID extension
	ImapClientVersion *string `json:"imapClientVersion,omitempty"`
	ImapIndexer *ImapIndexer `json:"imapIndexer,omitempty"`
	// Enable the IMAP proxy server
	ImapProxyServerEnabled *bool `json:"imapProxyServerEnabled,omitempty"`
	// IP address to bind the IMAP proxy to (empty = all interfaces)
	ImapProxyServerHost *string `json:"imapProxyServerHost,omitempty"`
	// Password for IMAP proxy authentication (null = disable authentication)
	ImapProxyServerPassword NullableString `json:"imapProxyServerPassword,omitempty"`
	// Port number for the IMAP proxy server
	ImapProxyServerPort *int32 `json:"imapProxyServerPort,omitempty"`
	// Enable PROXY protocol support for the IMAP proxy
	ImapProxyServerProxy *bool `json:"imapProxyServerProxy,omitempty"`
	// Enable TLS support for the IMAP proxy
	ImapProxyServerTLSEnabled *bool `json:"imapProxyServerTLSEnabled,omitempty"`
	ImapStrategy *ImapStrategy `json:"imapStrategy,omitempty"`
	// Trigger \"messageNew\" webhooks only for messages arriving in the Inbox folder
	InboxNewOnly *bool `json:"inboxNewOnly,omitempty"`
	// List of local IP addresses to use for outbound connections (requires appropriate network configuration)
	LocalAddresses []string `json:"localAddresses,omitempty"`
	Locale *Locale `json:"locale,omitempty"`
	Logs *LogSettings `json:"logs,omitempty"`
	// Public callback URL for external OAuth providers. Falls back to serviceUrl if not set
	NotificationBaseUrl NullableString `json:"notificationBaseUrl,omitempty"`
	// Maximum size (in bytes) per attachment to include in webhook payloads
	NotifyAttachmentSize *int32 `json:"notifyAttachmentSize,omitempty"`
	// Include attachment data in webhook payloads
	NotifyAttachments *bool `json:"notifyAttachments,omitempty"`
	// Include parsed calendar event data in webhook payloads
	NotifyCalendarEvents *bool `json:"notifyCalendarEvents,omitempty"`
	// Email headers to include in webhook payloads for additional context
	NotifyHeaders []string `json:"notifyHeaders,omitempty"`
	// Include plain text message content in webhook payloads
	NotifyText *bool `json:"notifyText,omitempty"`
	// Maximum size (in bytes) of text content to include in webhook payloads
	NotifyTextSize *int32 `json:"notifyTextSize,omitempty"`
	// Sanitize HTML content to remove potentially dangerous elements before including in webhooks
	NotifyWebSafeHtml *bool `json:"notifyWebSafeHtml,omitempty"`
	// Your OpenAI API key for AI features
	OpenAiAPIKey *string `json:"openAiAPIKey,omitempty"`
	// Base URL for OpenAI API (change for OpenAI-compatible services)
	OpenAiAPIUrl *string `json:"openAiAPIUrl,omitempty"`
	// Generate vector embeddings for semantic search and similarity matching
	OpenAiGenerateEmbeddings *bool `json:"openAiGenerateEmbeddings,omitempty"`
	// Maximum tokens limit for OpenAI API requests (defaults: GPT-5: 18000, GPT-4: 6500, GPT-3.5: 3000)
	OpenAiMaxTokens *float32 `json:"openAiMaxTokens,omitempty"`
	// OpenAI model to use for text generation
	OpenAiModel *string `json:"openAiModel,omitempty"`
	// JavaScript function to filter emails before AI processing (return true to process, false to skip)
	OpenAiPreProcessingFn *string `json:"openAiPreProcessingFn,omitempty"`
	// Custom system prompt to guide AI behavior when processing emails
	OpenAiPrompt *string `json:"openAiPrompt,omitempty"`
	// Controls randomness in AI responses (0 = deterministic, 2 = very creative)
	OpenAiTemperature *float32 `json:"openAiTemperature,omitempty"`
	// Nucleus sampling parameter for AI text generation (0-1, lower = more focused)
	OpenAiTopP *float32 `json:"openAiTopP,omitempty"`
	// Brand name displayed in page titles
	PageBrandName NullableString `json:"pageBrandName,omitempty"`
	// Route outbound connections through a proxy server
	ProxyEnabled *bool `json:"proxyEnabled,omitempty"`
	// Proxy server URL for outbound connections
	ProxyUrl *string `json:"proxyUrl,omitempty"`
	// Number of completed and failed queue entries to retain for debugging
	QueueKeep *int32 `json:"queueKeep,omitempty"`
	// Automatically detect and categorize Gmail tabs (Primary, Social, Promotions, etc.) for IMAP connections
	ResolveGmailCategories *bool `json:"resolveGmailCategories,omitempty"`
	// JSON object containing environment variables available to pre-processing scripts
	ScriptEnv *string `json:"scriptEnv,omitempty"`
	// HMAC secret for signing API requests and validating webhooks
	ServiceSecret *string `json:"serviceSecret,omitempty"`
	// Base URL of this EmailEngine instance (used for generating public URLs, path component is ignored)
	ServiceUrl *string `json:"serviceUrl,omitempty"`
	// Hostname to use in SMTP EHLO/HELO commands (defaults to system hostname)
	SmtpEhloName NullableString `json:"smtpEhloName,omitempty"`
	// Require SMTP authentication for incoming connections
	SmtpServerAuthEnabled *bool `json:"smtpServerAuthEnabled,omitempty"`
	// Enable the built-in SMTP server for receiving emails
	SmtpServerEnabled *bool `json:"smtpServerEnabled,omitempty"`
	// IP address to bind the SMTP server to (empty = all interfaces)
	SmtpServerHost *string `json:"smtpServerHost,omitempty"`
	// Password for SMTP authentication (null = disable authentication)
	SmtpServerPassword NullableString `json:"smtpServerPassword,omitempty"`
	// Port number for the built-in SMTP server
	SmtpServerPort *int32 `json:"smtpServerPort,omitempty"`
	// Enable PROXY protocol support for the SMTP server
	SmtpServerProxy *bool `json:"smtpServerProxy,omitempty"`
	// Enable TLS/STARTTLS support for the SMTP server
	SmtpServerTLSEnabled *bool `json:"smtpServerTLSEnabled,omitempty"`
	SmtpStrategy *SmtpStrategy `json:"smtpStrategy,omitempty"`
	// Custom HTML to inject at the top of hosted pages (e.g., for branding)
	TemplateHeader *string `json:"templateHeader,omitempty"`
	// Custom HTML to inject into the <head> section of hosted pages (e.g., for analytics)
	TemplateHtmlHead *string `json:"templateHtmlHead,omitempty"`
	// Default timezone for date/time display (IANA timezone identifier)
	Timezone *string `json:"timezone,omitempty"`
	// Rewrite links in outgoing HTML emails to track click-through rates
	TrackClicks *bool `json:"trackClicks,omitempty"`
	// Insert a tracking pixel in outgoing HTML emails to detect when messages are opened
	TrackOpens *bool `json:"trackOpens,omitempty"`
	// List of event types that will trigger webhook notifications
	WebhookEvents []string `json:"webhookEvents,omitempty"`
	// Target URL that will receive webhook notifications via POST requests
	Webhooks *string `json:"webhooks,omitempty"`
	// Additional HTTP headers to include with every webhook request for authentication or tracking
	WebhooksCustomHeaders []WebhooksCustomHeader `json:"webhooksCustomHeaders,omitempty"`
	// Enable or disable webhook delivery for all accounts
	WebhooksEnabled *bool `json:"webhooksEnabled,omitempty"`
}

// NewSettings instantiates a new Settings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettings() *Settings {
	this := Settings{}
	return &this
}

// NewSettingsWithDefaults instantiates a new Settings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettingsWithDefaults() *Settings {
	this := Settings{}
	return &this
}

// GetAuthServer returns the AuthServer field value if set, zero value otherwise.
func (o *Settings) GetAuthServer() string {
	if o == nil || IsNil(o.AuthServer) {
		var ret string
		return ret
	}
	return *o.AuthServer
}

// GetAuthServerOk returns a tuple with the AuthServer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetAuthServerOk() (*string, bool) {
	if o == nil || IsNil(o.AuthServer) {
		return nil, false
	}
	return o.AuthServer, true
}

// HasAuthServer returns a boolean if a field has been set.
func (o *Settings) HasAuthServer() bool {
	if o != nil && !IsNil(o.AuthServer) {
		return true
	}

	return false
}

// SetAuthServer gets a reference to the given string and assigns it to the AuthServer field.
func (o *Settings) SetAuthServer(v string) {
	o.AuthServer = &v
}

// GetDeliveryAttempts returns the DeliveryAttempts field value if set, zero value otherwise.
func (o *Settings) GetDeliveryAttempts() int32 {
	if o == nil || IsNil(o.DeliveryAttempts) {
		var ret int32
		return ret
	}
	return *o.DeliveryAttempts
}

// GetDeliveryAttemptsOk returns a tuple with the DeliveryAttempts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetDeliveryAttemptsOk() (*int32, bool) {
	if o == nil || IsNil(o.DeliveryAttempts) {
		return nil, false
	}
	return o.DeliveryAttempts, true
}

// HasDeliveryAttempts returns a boolean if a field has been set.
func (o *Settings) HasDeliveryAttempts() bool {
	if o != nil && !IsNil(o.DeliveryAttempts) {
		return true
	}

	return false
}

// SetDeliveryAttempts gets a reference to the given int32 and assigns it to the DeliveryAttempts field.
func (o *Settings) SetDeliveryAttempts(v int32) {
	o.DeliveryAttempts = &v
}

// GetEnableApiProxy returns the EnableApiProxy field value if set, zero value otherwise.
func (o *Settings) GetEnableApiProxy() bool {
	if o == nil || IsNil(o.EnableApiProxy) {
		var ret bool
		return ret
	}
	return *o.EnableApiProxy
}

// GetEnableApiProxyOk returns a tuple with the EnableApiProxy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetEnableApiProxyOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableApiProxy) {
		return nil, false
	}
	return o.EnableApiProxy, true
}

// HasEnableApiProxy returns a boolean if a field has been set.
func (o *Settings) HasEnableApiProxy() bool {
	if o != nil && !IsNil(o.EnableApiProxy) {
		return true
	}

	return false
}

// SetEnableApiProxy gets a reference to the given bool and assigns it to the EnableApiProxy field.
func (o *Settings) SetEnableApiProxy(v bool) {
	o.EnableApiProxy = &v
}

// GetGenerateEmailSummary returns the GenerateEmailSummary field value if set, zero value otherwise.
func (o *Settings) GetGenerateEmailSummary() bool {
	if o == nil || IsNil(o.GenerateEmailSummary) {
		var ret bool
		return ret
	}
	return *o.GenerateEmailSummary
}

// GetGenerateEmailSummaryOk returns a tuple with the GenerateEmailSummary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetGenerateEmailSummaryOk() (*bool, bool) {
	if o == nil || IsNil(o.GenerateEmailSummary) {
		return nil, false
	}
	return o.GenerateEmailSummary, true
}

// HasGenerateEmailSummary returns a boolean if a field has been set.
func (o *Settings) HasGenerateEmailSummary() bool {
	if o != nil && !IsNil(o.GenerateEmailSummary) {
		return true
	}

	return false
}

// SetGenerateEmailSummary gets a reference to the given bool and assigns it to the GenerateEmailSummary field.
func (o *Settings) SetGenerateEmailSummary(v bool) {
	o.GenerateEmailSummary = &v
}

// GetIgnoreMailCertErrors returns the IgnoreMailCertErrors field value if set, zero value otherwise.
func (o *Settings) GetIgnoreMailCertErrors() bool {
	if o == nil || IsNil(o.IgnoreMailCertErrors) {
		var ret bool
		return ret
	}
	return *o.IgnoreMailCertErrors
}

// GetIgnoreMailCertErrorsOk returns a tuple with the IgnoreMailCertErrors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetIgnoreMailCertErrorsOk() (*bool, bool) {
	if o == nil || IsNil(o.IgnoreMailCertErrors) {
		return nil, false
	}
	return o.IgnoreMailCertErrors, true
}

// HasIgnoreMailCertErrors returns a boolean if a field has been set.
func (o *Settings) HasIgnoreMailCertErrors() bool {
	if o != nil && !IsNil(o.IgnoreMailCertErrors) {
		return true
	}

	return false
}

// SetIgnoreMailCertErrors gets a reference to the given bool and assigns it to the IgnoreMailCertErrors field.
func (o *Settings) SetIgnoreMailCertErrors(v bool) {
	o.IgnoreMailCertErrors = &v
}

// GetImapClientName returns the ImapClientName field value if set, zero value otherwise.
func (o *Settings) GetImapClientName() string {
	if o == nil || IsNil(o.ImapClientName) {
		var ret string
		return ret
	}
	return *o.ImapClientName
}

// GetImapClientNameOk returns a tuple with the ImapClientName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetImapClientNameOk() (*string, bool) {
	if o == nil || IsNil(o.ImapClientName) {
		return nil, false
	}
	return o.ImapClientName, true
}

// HasImapClientName returns a boolean if a field has been set.
func (o *Settings) HasImapClientName() bool {
	if o != nil && !IsNil(o.ImapClientName) {
		return true
	}

	return false
}

// SetImapClientName gets a reference to the given string and assigns it to the ImapClientName field.
func (o *Settings) SetImapClientName(v string) {
	o.ImapClientName = &v
}

// GetImapClientSupportUrl returns the ImapClientSupportUrl field value if set, zero value otherwise.
func (o *Settings) GetImapClientSupportUrl() string {
	if o == nil || IsNil(o.ImapClientSupportUrl) {
		var ret string
		return ret
	}
	return *o.ImapClientSupportUrl
}

// GetImapClientSupportUrlOk returns a tuple with the ImapClientSupportUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetImapClientSupportUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ImapClientSupportUrl) {
		return nil, false
	}
	return o.ImapClientSupportUrl, true
}

// HasImapClientSupportUrl returns a boolean if a field has been set.
func (o *Settings) HasImapClientSupportUrl() bool {
	if o != nil && !IsNil(o.ImapClientSupportUrl) {
		return true
	}

	return false
}

// SetImapClientSupportUrl gets a reference to the given string and assigns it to the ImapClientSupportUrl field.
func (o *Settings) SetImapClientSupportUrl(v string) {
	o.ImapClientSupportUrl = &v
}

// GetImapClientVendor returns the ImapClientVendor field value if set, zero value otherwise.
func (o *Settings) GetImapClientVendor() string {
	if o == nil || IsNil(o.ImapClientVendor) {
		var ret string
		return ret
	}
	return *o.ImapClientVendor
}

// GetImapClientVendorOk returns a tuple with the ImapClientVendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetImapClientVendorOk() (*string, bool) {
	if o == nil || IsNil(o.ImapClientVendor) {
		return nil, false
	}
	return o.ImapClientVendor, true
}

// HasImapClientVendor returns a boolean if a field has been set.
func (o *Settings) HasImapClientVendor() bool {
	if o != nil && !IsNil(o.ImapClientVendor) {
		return true
	}

	return false
}

// SetImapClientVendor gets a reference to the given string and assigns it to the ImapClientVendor field.
func (o *Settings) SetImapClientVendor(v string) {
	o.ImapClientVendor = &v
}

// GetImapClientVersion returns the ImapClientVersion field value if set, zero value otherwise.
func (o *Settings) GetImapClientVersion() string {
	if o == nil || IsNil(o.ImapClientVersion) {
		var ret string
		return ret
	}
	return *o.ImapClientVersion
}

// GetImapClientVersionOk returns a tuple with the ImapClientVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetImapClientVersionOk() (*string, bool) {
	if o == nil || IsNil(o.ImapClientVersion) {
		return nil, false
	}
	return o.ImapClientVersion, true
}

// HasImapClientVersion returns a boolean if a field has been set.
func (o *Settings) HasImapClientVersion() bool {
	if o != nil && !IsNil(o.ImapClientVersion) {
		return true
	}

	return false
}

// SetImapClientVersion gets a reference to the given string and assigns it to the ImapClientVersion field.
func (o *Settings) SetImapClientVersion(v string) {
	o.ImapClientVersion = &v
}

// GetImapIndexer returns the ImapIndexer field value if set, zero value otherwise.
func (o *Settings) GetImapIndexer() ImapIndexer {
	if o == nil || IsNil(o.ImapIndexer) {
		var ret ImapIndexer
		return ret
	}
	return *o.ImapIndexer
}

// GetImapIndexerOk returns a tuple with the ImapIndexer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetImapIndexerOk() (*ImapIndexer, bool) {
	if o == nil || IsNil(o.ImapIndexer) {
		return nil, false
	}
	return o.ImapIndexer, true
}

// HasImapIndexer returns a boolean if a field has been set.
func (o *Settings) HasImapIndexer() bool {
	if o != nil && !IsNil(o.ImapIndexer) {
		return true
	}

	return false
}

// SetImapIndexer gets a reference to the given ImapIndexer and assigns it to the ImapIndexer field.
func (o *Settings) SetImapIndexer(v ImapIndexer) {
	o.ImapIndexer = &v
}

// GetImapProxyServerEnabled returns the ImapProxyServerEnabled field value if set, zero value otherwise.
func (o *Settings) GetImapProxyServerEnabled() bool {
	if o == nil || IsNil(o.ImapProxyServerEnabled) {
		var ret bool
		return ret
	}
	return *o.ImapProxyServerEnabled
}

// GetImapProxyServerEnabledOk returns a tuple with the ImapProxyServerEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetImapProxyServerEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.ImapProxyServerEnabled) {
		return nil, false
	}
	return o.ImapProxyServerEnabled, true
}

// HasImapProxyServerEnabled returns a boolean if a field has been set.
func (o *Settings) HasImapProxyServerEnabled() bool {
	if o != nil && !IsNil(o.ImapProxyServerEnabled) {
		return true
	}

	return false
}

// SetImapProxyServerEnabled gets a reference to the given bool and assigns it to the ImapProxyServerEnabled field.
func (o *Settings) SetImapProxyServerEnabled(v bool) {
	o.ImapProxyServerEnabled = &v
}

// GetImapProxyServerHost returns the ImapProxyServerHost field value if set, zero value otherwise.
func (o *Settings) GetImapProxyServerHost() string {
	if o == nil || IsNil(o.ImapProxyServerHost) {
		var ret string
		return ret
	}
	return *o.ImapProxyServerHost
}

// GetImapProxyServerHostOk returns a tuple with the ImapProxyServerHost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetImapProxyServerHostOk() (*string, bool) {
	if o == nil || IsNil(o.ImapProxyServerHost) {
		return nil, false
	}
	return o.ImapProxyServerHost, true
}

// HasImapProxyServerHost returns a boolean if a field has been set.
func (o *Settings) HasImapProxyServerHost() bool {
	if o != nil && !IsNil(o.ImapProxyServerHost) {
		return true
	}

	return false
}

// SetImapProxyServerHost gets a reference to the given string and assigns it to the ImapProxyServerHost field.
func (o *Settings) SetImapProxyServerHost(v string) {
	o.ImapProxyServerHost = &v
}

// GetImapProxyServerPassword returns the ImapProxyServerPassword field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Settings) GetImapProxyServerPassword() string {
	if o == nil || IsNil(o.ImapProxyServerPassword.Get()) {
		var ret string
		return ret
	}
	return *o.ImapProxyServerPassword.Get()
}

// GetImapProxyServerPasswordOk returns a tuple with the ImapProxyServerPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Settings) GetImapProxyServerPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ImapProxyServerPassword.Get(), o.ImapProxyServerPassword.IsSet()
}

// HasImapProxyServerPassword returns a boolean if a field has been set.
func (o *Settings) HasImapProxyServerPassword() bool {
	if o != nil && o.ImapProxyServerPassword.IsSet() {
		return true
	}

	return false
}

// SetImapProxyServerPassword gets a reference to the given NullableString and assigns it to the ImapProxyServerPassword field.
func (o *Settings) SetImapProxyServerPassword(v string) {
	o.ImapProxyServerPassword.Set(&v)
}
// SetImapProxyServerPasswordNil sets the value for ImapProxyServerPassword to be an explicit nil
func (o *Settings) SetImapProxyServerPasswordNil() {
	o.ImapProxyServerPassword.Set(nil)
}

// UnsetImapProxyServerPassword ensures that no value is present for ImapProxyServerPassword, not even an explicit nil
func (o *Settings) UnsetImapProxyServerPassword() {
	o.ImapProxyServerPassword.Unset()
}

// GetImapProxyServerPort returns the ImapProxyServerPort field value if set, zero value otherwise.
func (o *Settings) GetImapProxyServerPort() int32 {
	if o == nil || IsNil(o.ImapProxyServerPort) {
		var ret int32
		return ret
	}
	return *o.ImapProxyServerPort
}

// GetImapProxyServerPortOk returns a tuple with the ImapProxyServerPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetImapProxyServerPortOk() (*int32, bool) {
	if o == nil || IsNil(o.ImapProxyServerPort) {
		return nil, false
	}
	return o.ImapProxyServerPort, true
}

// HasImapProxyServerPort returns a boolean if a field has been set.
func (o *Settings) HasImapProxyServerPort() bool {
	if o != nil && !IsNil(o.ImapProxyServerPort) {
		return true
	}

	return false
}

// SetImapProxyServerPort gets a reference to the given int32 and assigns it to the ImapProxyServerPort field.
func (o *Settings) SetImapProxyServerPort(v int32) {
	o.ImapProxyServerPort = &v
}

// GetImapProxyServerProxy returns the ImapProxyServerProxy field value if set, zero value otherwise.
func (o *Settings) GetImapProxyServerProxy() bool {
	if o == nil || IsNil(o.ImapProxyServerProxy) {
		var ret bool
		return ret
	}
	return *o.ImapProxyServerProxy
}

// GetImapProxyServerProxyOk returns a tuple with the ImapProxyServerProxy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetImapProxyServerProxyOk() (*bool, bool) {
	if o == nil || IsNil(o.ImapProxyServerProxy) {
		return nil, false
	}
	return o.ImapProxyServerProxy, true
}

// HasImapProxyServerProxy returns a boolean if a field has been set.
func (o *Settings) HasImapProxyServerProxy() bool {
	if o != nil && !IsNil(o.ImapProxyServerProxy) {
		return true
	}

	return false
}

// SetImapProxyServerProxy gets a reference to the given bool and assigns it to the ImapProxyServerProxy field.
func (o *Settings) SetImapProxyServerProxy(v bool) {
	o.ImapProxyServerProxy = &v
}

// GetImapProxyServerTLSEnabled returns the ImapProxyServerTLSEnabled field value if set, zero value otherwise.
func (o *Settings) GetImapProxyServerTLSEnabled() bool {
	if o == nil || IsNil(o.ImapProxyServerTLSEnabled) {
		var ret bool
		return ret
	}
	return *o.ImapProxyServerTLSEnabled
}

// GetImapProxyServerTLSEnabledOk returns a tuple with the ImapProxyServerTLSEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetImapProxyServerTLSEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.ImapProxyServerTLSEnabled) {
		return nil, false
	}
	return o.ImapProxyServerTLSEnabled, true
}

// HasImapProxyServerTLSEnabled returns a boolean if a field has been set.
func (o *Settings) HasImapProxyServerTLSEnabled() bool {
	if o != nil && !IsNil(o.ImapProxyServerTLSEnabled) {
		return true
	}

	return false
}

// SetImapProxyServerTLSEnabled gets a reference to the given bool and assigns it to the ImapProxyServerTLSEnabled field.
func (o *Settings) SetImapProxyServerTLSEnabled(v bool) {
	o.ImapProxyServerTLSEnabled = &v
}

// GetImapStrategy returns the ImapStrategy field value if set, zero value otherwise.
func (o *Settings) GetImapStrategy() ImapStrategy {
	if o == nil || IsNil(o.ImapStrategy) {
		var ret ImapStrategy
		return ret
	}
	return *o.ImapStrategy
}

// GetImapStrategyOk returns a tuple with the ImapStrategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetImapStrategyOk() (*ImapStrategy, bool) {
	if o == nil || IsNil(o.ImapStrategy) {
		return nil, false
	}
	return o.ImapStrategy, true
}

// HasImapStrategy returns a boolean if a field has been set.
func (o *Settings) HasImapStrategy() bool {
	if o != nil && !IsNil(o.ImapStrategy) {
		return true
	}

	return false
}

// SetImapStrategy gets a reference to the given ImapStrategy and assigns it to the ImapStrategy field.
func (o *Settings) SetImapStrategy(v ImapStrategy) {
	o.ImapStrategy = &v
}

// GetInboxNewOnly returns the InboxNewOnly field value if set, zero value otherwise.
func (o *Settings) GetInboxNewOnly() bool {
	if o == nil || IsNil(o.InboxNewOnly) {
		var ret bool
		return ret
	}
	return *o.InboxNewOnly
}

// GetInboxNewOnlyOk returns a tuple with the InboxNewOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetInboxNewOnlyOk() (*bool, bool) {
	if o == nil || IsNil(o.InboxNewOnly) {
		return nil, false
	}
	return o.InboxNewOnly, true
}

// HasInboxNewOnly returns a boolean if a field has been set.
func (o *Settings) HasInboxNewOnly() bool {
	if o != nil && !IsNil(o.InboxNewOnly) {
		return true
	}

	return false
}

// SetInboxNewOnly gets a reference to the given bool and assigns it to the InboxNewOnly field.
func (o *Settings) SetInboxNewOnly(v bool) {
	o.InboxNewOnly = &v
}

// GetLocalAddresses returns the LocalAddresses field value if set, zero value otherwise.
func (o *Settings) GetLocalAddresses() []string {
	if o == nil || IsNil(o.LocalAddresses) {
		var ret []string
		return ret
	}
	return o.LocalAddresses
}

// GetLocalAddressesOk returns a tuple with the LocalAddresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetLocalAddressesOk() ([]string, bool) {
	if o == nil || IsNil(o.LocalAddresses) {
		return nil, false
	}
	return o.LocalAddresses, true
}

// HasLocalAddresses returns a boolean if a field has been set.
func (o *Settings) HasLocalAddresses() bool {
	if o != nil && !IsNil(o.LocalAddresses) {
		return true
	}

	return false
}

// SetLocalAddresses gets a reference to the given []string and assigns it to the LocalAddresses field.
func (o *Settings) SetLocalAddresses(v []string) {
	o.LocalAddresses = v
}

// GetLocale returns the Locale field value if set, zero value otherwise.
func (o *Settings) GetLocale() Locale {
	if o == nil || IsNil(o.Locale) {
		var ret Locale
		return ret
	}
	return *o.Locale
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetLocaleOk() (*Locale, bool) {
	if o == nil || IsNil(o.Locale) {
		return nil, false
	}
	return o.Locale, true
}

// HasLocale returns a boolean if a field has been set.
func (o *Settings) HasLocale() bool {
	if o != nil && !IsNil(o.Locale) {
		return true
	}

	return false
}

// SetLocale gets a reference to the given Locale and assigns it to the Locale field.
func (o *Settings) SetLocale(v Locale) {
	o.Locale = &v
}

// GetLogs returns the Logs field value if set, zero value otherwise.
func (o *Settings) GetLogs() LogSettings {
	if o == nil || IsNil(o.Logs) {
		var ret LogSettings
		return ret
	}
	return *o.Logs
}

// GetLogsOk returns a tuple with the Logs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetLogsOk() (*LogSettings, bool) {
	if o == nil || IsNil(o.Logs) {
		return nil, false
	}
	return o.Logs, true
}

// HasLogs returns a boolean if a field has been set.
func (o *Settings) HasLogs() bool {
	if o != nil && !IsNil(o.Logs) {
		return true
	}

	return false
}

// SetLogs gets a reference to the given LogSettings and assigns it to the Logs field.
func (o *Settings) SetLogs(v LogSettings) {
	o.Logs = &v
}

// GetNotificationBaseUrl returns the NotificationBaseUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Settings) GetNotificationBaseUrl() string {
	if o == nil || IsNil(o.NotificationBaseUrl.Get()) {
		var ret string
		return ret
	}
	return *o.NotificationBaseUrl.Get()
}

// GetNotificationBaseUrlOk returns a tuple with the NotificationBaseUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Settings) GetNotificationBaseUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NotificationBaseUrl.Get(), o.NotificationBaseUrl.IsSet()
}

// HasNotificationBaseUrl returns a boolean if a field has been set.
func (o *Settings) HasNotificationBaseUrl() bool {
	if o != nil && o.NotificationBaseUrl.IsSet() {
		return true
	}

	return false
}

// SetNotificationBaseUrl gets a reference to the given NullableString and assigns it to the NotificationBaseUrl field.
func (o *Settings) SetNotificationBaseUrl(v string) {
	o.NotificationBaseUrl.Set(&v)
}
// SetNotificationBaseUrlNil sets the value for NotificationBaseUrl to be an explicit nil
func (o *Settings) SetNotificationBaseUrlNil() {
	o.NotificationBaseUrl.Set(nil)
}

// UnsetNotificationBaseUrl ensures that no value is present for NotificationBaseUrl, not even an explicit nil
func (o *Settings) UnsetNotificationBaseUrl() {
	o.NotificationBaseUrl.Unset()
}

// GetNotifyAttachmentSize returns the NotifyAttachmentSize field value if set, zero value otherwise.
func (o *Settings) GetNotifyAttachmentSize() int32 {
	if o == nil || IsNil(o.NotifyAttachmentSize) {
		var ret int32
		return ret
	}
	return *o.NotifyAttachmentSize
}

// GetNotifyAttachmentSizeOk returns a tuple with the NotifyAttachmentSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetNotifyAttachmentSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.NotifyAttachmentSize) {
		return nil, false
	}
	return o.NotifyAttachmentSize, true
}

// HasNotifyAttachmentSize returns a boolean if a field has been set.
func (o *Settings) HasNotifyAttachmentSize() bool {
	if o != nil && !IsNil(o.NotifyAttachmentSize) {
		return true
	}

	return false
}

// SetNotifyAttachmentSize gets a reference to the given int32 and assigns it to the NotifyAttachmentSize field.
func (o *Settings) SetNotifyAttachmentSize(v int32) {
	o.NotifyAttachmentSize = &v
}

// GetNotifyAttachments returns the NotifyAttachments field value if set, zero value otherwise.
func (o *Settings) GetNotifyAttachments() bool {
	if o == nil || IsNil(o.NotifyAttachments) {
		var ret bool
		return ret
	}
	return *o.NotifyAttachments
}

// GetNotifyAttachmentsOk returns a tuple with the NotifyAttachments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetNotifyAttachmentsOk() (*bool, bool) {
	if o == nil || IsNil(o.NotifyAttachments) {
		return nil, false
	}
	return o.NotifyAttachments, true
}

// HasNotifyAttachments returns a boolean if a field has been set.
func (o *Settings) HasNotifyAttachments() bool {
	if o != nil && !IsNil(o.NotifyAttachments) {
		return true
	}

	return false
}

// SetNotifyAttachments gets a reference to the given bool and assigns it to the NotifyAttachments field.
func (o *Settings) SetNotifyAttachments(v bool) {
	o.NotifyAttachments = &v
}

// GetNotifyCalendarEvents returns the NotifyCalendarEvents field value if set, zero value otherwise.
func (o *Settings) GetNotifyCalendarEvents() bool {
	if o == nil || IsNil(o.NotifyCalendarEvents) {
		var ret bool
		return ret
	}
	return *o.NotifyCalendarEvents
}

// GetNotifyCalendarEventsOk returns a tuple with the NotifyCalendarEvents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetNotifyCalendarEventsOk() (*bool, bool) {
	if o == nil || IsNil(o.NotifyCalendarEvents) {
		return nil, false
	}
	return o.NotifyCalendarEvents, true
}

// HasNotifyCalendarEvents returns a boolean if a field has been set.
func (o *Settings) HasNotifyCalendarEvents() bool {
	if o != nil && !IsNil(o.NotifyCalendarEvents) {
		return true
	}

	return false
}

// SetNotifyCalendarEvents gets a reference to the given bool and assigns it to the NotifyCalendarEvents field.
func (o *Settings) SetNotifyCalendarEvents(v bool) {
	o.NotifyCalendarEvents = &v
}

// GetNotifyHeaders returns the NotifyHeaders field value if set, zero value otherwise.
func (o *Settings) GetNotifyHeaders() []string {
	if o == nil || IsNil(o.NotifyHeaders) {
		var ret []string
		return ret
	}
	return o.NotifyHeaders
}

// GetNotifyHeadersOk returns a tuple with the NotifyHeaders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetNotifyHeadersOk() ([]string, bool) {
	if o == nil || IsNil(o.NotifyHeaders) {
		return nil, false
	}
	return o.NotifyHeaders, true
}

// HasNotifyHeaders returns a boolean if a field has been set.
func (o *Settings) HasNotifyHeaders() bool {
	if o != nil && !IsNil(o.NotifyHeaders) {
		return true
	}

	return false
}

// SetNotifyHeaders gets a reference to the given []string and assigns it to the NotifyHeaders field.
func (o *Settings) SetNotifyHeaders(v []string) {
	o.NotifyHeaders = v
}

// GetNotifyText returns the NotifyText field value if set, zero value otherwise.
func (o *Settings) GetNotifyText() bool {
	if o == nil || IsNil(o.NotifyText) {
		var ret bool
		return ret
	}
	return *o.NotifyText
}

// GetNotifyTextOk returns a tuple with the NotifyText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetNotifyTextOk() (*bool, bool) {
	if o == nil || IsNil(o.NotifyText) {
		return nil, false
	}
	return o.NotifyText, true
}

// HasNotifyText returns a boolean if a field has been set.
func (o *Settings) HasNotifyText() bool {
	if o != nil && !IsNil(o.NotifyText) {
		return true
	}

	return false
}

// SetNotifyText gets a reference to the given bool and assigns it to the NotifyText field.
func (o *Settings) SetNotifyText(v bool) {
	o.NotifyText = &v
}

// GetNotifyTextSize returns the NotifyTextSize field value if set, zero value otherwise.
func (o *Settings) GetNotifyTextSize() int32 {
	if o == nil || IsNil(o.NotifyTextSize) {
		var ret int32
		return ret
	}
	return *o.NotifyTextSize
}

// GetNotifyTextSizeOk returns a tuple with the NotifyTextSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetNotifyTextSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.NotifyTextSize) {
		return nil, false
	}
	return o.NotifyTextSize, true
}

// HasNotifyTextSize returns a boolean if a field has been set.
func (o *Settings) HasNotifyTextSize() bool {
	if o != nil && !IsNil(o.NotifyTextSize) {
		return true
	}

	return false
}

// SetNotifyTextSize gets a reference to the given int32 and assigns it to the NotifyTextSize field.
func (o *Settings) SetNotifyTextSize(v int32) {
	o.NotifyTextSize = &v
}

// GetNotifyWebSafeHtml returns the NotifyWebSafeHtml field value if set, zero value otherwise.
func (o *Settings) GetNotifyWebSafeHtml() bool {
	if o == nil || IsNil(o.NotifyWebSafeHtml) {
		var ret bool
		return ret
	}
	return *o.NotifyWebSafeHtml
}

// GetNotifyWebSafeHtmlOk returns a tuple with the NotifyWebSafeHtml field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetNotifyWebSafeHtmlOk() (*bool, bool) {
	if o == nil || IsNil(o.NotifyWebSafeHtml) {
		return nil, false
	}
	return o.NotifyWebSafeHtml, true
}

// HasNotifyWebSafeHtml returns a boolean if a field has been set.
func (o *Settings) HasNotifyWebSafeHtml() bool {
	if o != nil && !IsNil(o.NotifyWebSafeHtml) {
		return true
	}

	return false
}

// SetNotifyWebSafeHtml gets a reference to the given bool and assigns it to the NotifyWebSafeHtml field.
func (o *Settings) SetNotifyWebSafeHtml(v bool) {
	o.NotifyWebSafeHtml = &v
}

// GetOpenAiAPIKey returns the OpenAiAPIKey field value if set, zero value otherwise.
func (o *Settings) GetOpenAiAPIKey() string {
	if o == nil || IsNil(o.OpenAiAPIKey) {
		var ret string
		return ret
	}
	return *o.OpenAiAPIKey
}

// GetOpenAiAPIKeyOk returns a tuple with the OpenAiAPIKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetOpenAiAPIKeyOk() (*string, bool) {
	if o == nil || IsNil(o.OpenAiAPIKey) {
		return nil, false
	}
	return o.OpenAiAPIKey, true
}

// HasOpenAiAPIKey returns a boolean if a field has been set.
func (o *Settings) HasOpenAiAPIKey() bool {
	if o != nil && !IsNil(o.OpenAiAPIKey) {
		return true
	}

	return false
}

// SetOpenAiAPIKey gets a reference to the given string and assigns it to the OpenAiAPIKey field.
func (o *Settings) SetOpenAiAPIKey(v string) {
	o.OpenAiAPIKey = &v
}

// GetOpenAiAPIUrl returns the OpenAiAPIUrl field value if set, zero value otherwise.
func (o *Settings) GetOpenAiAPIUrl() string {
	if o == nil || IsNil(o.OpenAiAPIUrl) {
		var ret string
		return ret
	}
	return *o.OpenAiAPIUrl
}

// GetOpenAiAPIUrlOk returns a tuple with the OpenAiAPIUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetOpenAiAPIUrlOk() (*string, bool) {
	if o == nil || IsNil(o.OpenAiAPIUrl) {
		return nil, false
	}
	return o.OpenAiAPIUrl, true
}

// HasOpenAiAPIUrl returns a boolean if a field has been set.
func (o *Settings) HasOpenAiAPIUrl() bool {
	if o != nil && !IsNil(o.OpenAiAPIUrl) {
		return true
	}

	return false
}

// SetOpenAiAPIUrl gets a reference to the given string and assigns it to the OpenAiAPIUrl field.
func (o *Settings) SetOpenAiAPIUrl(v string) {
	o.OpenAiAPIUrl = &v
}

// GetOpenAiGenerateEmbeddings returns the OpenAiGenerateEmbeddings field value if set, zero value otherwise.
func (o *Settings) GetOpenAiGenerateEmbeddings() bool {
	if o == nil || IsNil(o.OpenAiGenerateEmbeddings) {
		var ret bool
		return ret
	}
	return *o.OpenAiGenerateEmbeddings
}

// GetOpenAiGenerateEmbeddingsOk returns a tuple with the OpenAiGenerateEmbeddings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetOpenAiGenerateEmbeddingsOk() (*bool, bool) {
	if o == nil || IsNil(o.OpenAiGenerateEmbeddings) {
		return nil, false
	}
	return o.OpenAiGenerateEmbeddings, true
}

// HasOpenAiGenerateEmbeddings returns a boolean if a field has been set.
func (o *Settings) HasOpenAiGenerateEmbeddings() bool {
	if o != nil && !IsNil(o.OpenAiGenerateEmbeddings) {
		return true
	}

	return false
}

// SetOpenAiGenerateEmbeddings gets a reference to the given bool and assigns it to the OpenAiGenerateEmbeddings field.
func (o *Settings) SetOpenAiGenerateEmbeddings(v bool) {
	o.OpenAiGenerateEmbeddings = &v
}

// GetOpenAiMaxTokens returns the OpenAiMaxTokens field value if set, zero value otherwise.
func (o *Settings) GetOpenAiMaxTokens() float32 {
	if o == nil || IsNil(o.OpenAiMaxTokens) {
		var ret float32
		return ret
	}
	return *o.OpenAiMaxTokens
}

// GetOpenAiMaxTokensOk returns a tuple with the OpenAiMaxTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetOpenAiMaxTokensOk() (*float32, bool) {
	if o == nil || IsNil(o.OpenAiMaxTokens) {
		return nil, false
	}
	return o.OpenAiMaxTokens, true
}

// HasOpenAiMaxTokens returns a boolean if a field has been set.
func (o *Settings) HasOpenAiMaxTokens() bool {
	if o != nil && !IsNil(o.OpenAiMaxTokens) {
		return true
	}

	return false
}

// SetOpenAiMaxTokens gets a reference to the given float32 and assigns it to the OpenAiMaxTokens field.
func (o *Settings) SetOpenAiMaxTokens(v float32) {
	o.OpenAiMaxTokens = &v
}

// GetOpenAiModel returns the OpenAiModel field value if set, zero value otherwise.
func (o *Settings) GetOpenAiModel() string {
	if o == nil || IsNil(o.OpenAiModel) {
		var ret string
		return ret
	}
	return *o.OpenAiModel
}

// GetOpenAiModelOk returns a tuple with the OpenAiModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetOpenAiModelOk() (*string, bool) {
	if o == nil || IsNil(o.OpenAiModel) {
		return nil, false
	}
	return o.OpenAiModel, true
}

// HasOpenAiModel returns a boolean if a field has been set.
func (o *Settings) HasOpenAiModel() bool {
	if o != nil && !IsNil(o.OpenAiModel) {
		return true
	}

	return false
}

// SetOpenAiModel gets a reference to the given string and assigns it to the OpenAiModel field.
func (o *Settings) SetOpenAiModel(v string) {
	o.OpenAiModel = &v
}

// GetOpenAiPreProcessingFn returns the OpenAiPreProcessingFn field value if set, zero value otherwise.
func (o *Settings) GetOpenAiPreProcessingFn() string {
	if o == nil || IsNil(o.OpenAiPreProcessingFn) {
		var ret string
		return ret
	}
	return *o.OpenAiPreProcessingFn
}

// GetOpenAiPreProcessingFnOk returns a tuple with the OpenAiPreProcessingFn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetOpenAiPreProcessingFnOk() (*string, bool) {
	if o == nil || IsNil(o.OpenAiPreProcessingFn) {
		return nil, false
	}
	return o.OpenAiPreProcessingFn, true
}

// HasOpenAiPreProcessingFn returns a boolean if a field has been set.
func (o *Settings) HasOpenAiPreProcessingFn() bool {
	if o != nil && !IsNil(o.OpenAiPreProcessingFn) {
		return true
	}

	return false
}

// SetOpenAiPreProcessingFn gets a reference to the given string and assigns it to the OpenAiPreProcessingFn field.
func (o *Settings) SetOpenAiPreProcessingFn(v string) {
	o.OpenAiPreProcessingFn = &v
}

// GetOpenAiPrompt returns the OpenAiPrompt field value if set, zero value otherwise.
func (o *Settings) GetOpenAiPrompt() string {
	if o == nil || IsNil(o.OpenAiPrompt) {
		var ret string
		return ret
	}
	return *o.OpenAiPrompt
}

// GetOpenAiPromptOk returns a tuple with the OpenAiPrompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetOpenAiPromptOk() (*string, bool) {
	if o == nil || IsNil(o.OpenAiPrompt) {
		return nil, false
	}
	return o.OpenAiPrompt, true
}

// HasOpenAiPrompt returns a boolean if a field has been set.
func (o *Settings) HasOpenAiPrompt() bool {
	if o != nil && !IsNil(o.OpenAiPrompt) {
		return true
	}

	return false
}

// SetOpenAiPrompt gets a reference to the given string and assigns it to the OpenAiPrompt field.
func (o *Settings) SetOpenAiPrompt(v string) {
	o.OpenAiPrompt = &v
}

// GetOpenAiTemperature returns the OpenAiTemperature field value if set, zero value otherwise.
func (o *Settings) GetOpenAiTemperature() float32 {
	if o == nil || IsNil(o.OpenAiTemperature) {
		var ret float32
		return ret
	}
	return *o.OpenAiTemperature
}

// GetOpenAiTemperatureOk returns a tuple with the OpenAiTemperature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetOpenAiTemperatureOk() (*float32, bool) {
	if o == nil || IsNil(o.OpenAiTemperature) {
		return nil, false
	}
	return o.OpenAiTemperature, true
}

// HasOpenAiTemperature returns a boolean if a field has been set.
func (o *Settings) HasOpenAiTemperature() bool {
	if o != nil && !IsNil(o.OpenAiTemperature) {
		return true
	}

	return false
}

// SetOpenAiTemperature gets a reference to the given float32 and assigns it to the OpenAiTemperature field.
func (o *Settings) SetOpenAiTemperature(v float32) {
	o.OpenAiTemperature = &v
}

// GetOpenAiTopP returns the OpenAiTopP field value if set, zero value otherwise.
func (o *Settings) GetOpenAiTopP() float32 {
	if o == nil || IsNil(o.OpenAiTopP) {
		var ret float32
		return ret
	}
	return *o.OpenAiTopP
}

// GetOpenAiTopPOk returns a tuple with the OpenAiTopP field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetOpenAiTopPOk() (*float32, bool) {
	if o == nil || IsNil(o.OpenAiTopP) {
		return nil, false
	}
	return o.OpenAiTopP, true
}

// HasOpenAiTopP returns a boolean if a field has been set.
func (o *Settings) HasOpenAiTopP() bool {
	if o != nil && !IsNil(o.OpenAiTopP) {
		return true
	}

	return false
}

// SetOpenAiTopP gets a reference to the given float32 and assigns it to the OpenAiTopP field.
func (o *Settings) SetOpenAiTopP(v float32) {
	o.OpenAiTopP = &v
}

// GetPageBrandName returns the PageBrandName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Settings) GetPageBrandName() string {
	if o == nil || IsNil(o.PageBrandName.Get()) {
		var ret string
		return ret
	}
	return *o.PageBrandName.Get()
}

// GetPageBrandNameOk returns a tuple with the PageBrandName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Settings) GetPageBrandNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PageBrandName.Get(), o.PageBrandName.IsSet()
}

// HasPageBrandName returns a boolean if a field has been set.
func (o *Settings) HasPageBrandName() bool {
	if o != nil && o.PageBrandName.IsSet() {
		return true
	}

	return false
}

// SetPageBrandName gets a reference to the given NullableString and assigns it to the PageBrandName field.
func (o *Settings) SetPageBrandName(v string) {
	o.PageBrandName.Set(&v)
}
// SetPageBrandNameNil sets the value for PageBrandName to be an explicit nil
func (o *Settings) SetPageBrandNameNil() {
	o.PageBrandName.Set(nil)
}

// UnsetPageBrandName ensures that no value is present for PageBrandName, not even an explicit nil
func (o *Settings) UnsetPageBrandName() {
	o.PageBrandName.Unset()
}

// GetProxyEnabled returns the ProxyEnabled field value if set, zero value otherwise.
func (o *Settings) GetProxyEnabled() bool {
	if o == nil || IsNil(o.ProxyEnabled) {
		var ret bool
		return ret
	}
	return *o.ProxyEnabled
}

// GetProxyEnabledOk returns a tuple with the ProxyEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetProxyEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.ProxyEnabled) {
		return nil, false
	}
	return o.ProxyEnabled, true
}

// HasProxyEnabled returns a boolean if a field has been set.
func (o *Settings) HasProxyEnabled() bool {
	if o != nil && !IsNil(o.ProxyEnabled) {
		return true
	}

	return false
}

// SetProxyEnabled gets a reference to the given bool and assigns it to the ProxyEnabled field.
func (o *Settings) SetProxyEnabled(v bool) {
	o.ProxyEnabled = &v
}

// GetProxyUrl returns the ProxyUrl field value if set, zero value otherwise.
func (o *Settings) GetProxyUrl() string {
	if o == nil || IsNil(o.ProxyUrl) {
		var ret string
		return ret
	}
	return *o.ProxyUrl
}

// GetProxyUrlOk returns a tuple with the ProxyUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetProxyUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ProxyUrl) {
		return nil, false
	}
	return o.ProxyUrl, true
}

// HasProxyUrl returns a boolean if a field has been set.
func (o *Settings) HasProxyUrl() bool {
	if o != nil && !IsNil(o.ProxyUrl) {
		return true
	}

	return false
}

// SetProxyUrl gets a reference to the given string and assigns it to the ProxyUrl field.
func (o *Settings) SetProxyUrl(v string) {
	o.ProxyUrl = &v
}

// GetQueueKeep returns the QueueKeep field value if set, zero value otherwise.
func (o *Settings) GetQueueKeep() int32 {
	if o == nil || IsNil(o.QueueKeep) {
		var ret int32
		return ret
	}
	return *o.QueueKeep
}

// GetQueueKeepOk returns a tuple with the QueueKeep field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetQueueKeepOk() (*int32, bool) {
	if o == nil || IsNil(o.QueueKeep) {
		return nil, false
	}
	return o.QueueKeep, true
}

// HasQueueKeep returns a boolean if a field has been set.
func (o *Settings) HasQueueKeep() bool {
	if o != nil && !IsNil(o.QueueKeep) {
		return true
	}

	return false
}

// SetQueueKeep gets a reference to the given int32 and assigns it to the QueueKeep field.
func (o *Settings) SetQueueKeep(v int32) {
	o.QueueKeep = &v
}

// GetResolveGmailCategories returns the ResolveGmailCategories field value if set, zero value otherwise.
func (o *Settings) GetResolveGmailCategories() bool {
	if o == nil || IsNil(o.ResolveGmailCategories) {
		var ret bool
		return ret
	}
	return *o.ResolveGmailCategories
}

// GetResolveGmailCategoriesOk returns a tuple with the ResolveGmailCategories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetResolveGmailCategoriesOk() (*bool, bool) {
	if o == nil || IsNil(o.ResolveGmailCategories) {
		return nil, false
	}
	return o.ResolveGmailCategories, true
}

// HasResolveGmailCategories returns a boolean if a field has been set.
func (o *Settings) HasResolveGmailCategories() bool {
	if o != nil && !IsNil(o.ResolveGmailCategories) {
		return true
	}

	return false
}

// SetResolveGmailCategories gets a reference to the given bool and assigns it to the ResolveGmailCategories field.
func (o *Settings) SetResolveGmailCategories(v bool) {
	o.ResolveGmailCategories = &v
}

// GetScriptEnv returns the ScriptEnv field value if set, zero value otherwise.
func (o *Settings) GetScriptEnv() string {
	if o == nil || IsNil(o.ScriptEnv) {
		var ret string
		return ret
	}
	return *o.ScriptEnv
}

// GetScriptEnvOk returns a tuple with the ScriptEnv field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetScriptEnvOk() (*string, bool) {
	if o == nil || IsNil(o.ScriptEnv) {
		return nil, false
	}
	return o.ScriptEnv, true
}

// HasScriptEnv returns a boolean if a field has been set.
func (o *Settings) HasScriptEnv() bool {
	if o != nil && !IsNil(o.ScriptEnv) {
		return true
	}

	return false
}

// SetScriptEnv gets a reference to the given string and assigns it to the ScriptEnv field.
func (o *Settings) SetScriptEnv(v string) {
	o.ScriptEnv = &v
}

// GetServiceSecret returns the ServiceSecret field value if set, zero value otherwise.
func (o *Settings) GetServiceSecret() string {
	if o == nil || IsNil(o.ServiceSecret) {
		var ret string
		return ret
	}
	return *o.ServiceSecret
}

// GetServiceSecretOk returns a tuple with the ServiceSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetServiceSecretOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceSecret) {
		return nil, false
	}
	return o.ServiceSecret, true
}

// HasServiceSecret returns a boolean if a field has been set.
func (o *Settings) HasServiceSecret() bool {
	if o != nil && !IsNil(o.ServiceSecret) {
		return true
	}

	return false
}

// SetServiceSecret gets a reference to the given string and assigns it to the ServiceSecret field.
func (o *Settings) SetServiceSecret(v string) {
	o.ServiceSecret = &v
}

// GetServiceUrl returns the ServiceUrl field value if set, zero value otherwise.
func (o *Settings) GetServiceUrl() string {
	if o == nil || IsNil(o.ServiceUrl) {
		var ret string
		return ret
	}
	return *o.ServiceUrl
}

// GetServiceUrlOk returns a tuple with the ServiceUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetServiceUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceUrl) {
		return nil, false
	}
	return o.ServiceUrl, true
}

// HasServiceUrl returns a boolean if a field has been set.
func (o *Settings) HasServiceUrl() bool {
	if o != nil && !IsNil(o.ServiceUrl) {
		return true
	}

	return false
}

// SetServiceUrl gets a reference to the given string and assigns it to the ServiceUrl field.
func (o *Settings) SetServiceUrl(v string) {
	o.ServiceUrl = &v
}

// GetSmtpEhloName returns the SmtpEhloName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Settings) GetSmtpEhloName() string {
	if o == nil || IsNil(o.SmtpEhloName.Get()) {
		var ret string
		return ret
	}
	return *o.SmtpEhloName.Get()
}

// GetSmtpEhloNameOk returns a tuple with the SmtpEhloName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Settings) GetSmtpEhloNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SmtpEhloName.Get(), o.SmtpEhloName.IsSet()
}

// HasSmtpEhloName returns a boolean if a field has been set.
func (o *Settings) HasSmtpEhloName() bool {
	if o != nil && o.SmtpEhloName.IsSet() {
		return true
	}

	return false
}

// SetSmtpEhloName gets a reference to the given NullableString and assigns it to the SmtpEhloName field.
func (o *Settings) SetSmtpEhloName(v string) {
	o.SmtpEhloName.Set(&v)
}
// SetSmtpEhloNameNil sets the value for SmtpEhloName to be an explicit nil
func (o *Settings) SetSmtpEhloNameNil() {
	o.SmtpEhloName.Set(nil)
}

// UnsetSmtpEhloName ensures that no value is present for SmtpEhloName, not even an explicit nil
func (o *Settings) UnsetSmtpEhloName() {
	o.SmtpEhloName.Unset()
}

// GetSmtpServerAuthEnabled returns the SmtpServerAuthEnabled field value if set, zero value otherwise.
func (o *Settings) GetSmtpServerAuthEnabled() bool {
	if o == nil || IsNil(o.SmtpServerAuthEnabled) {
		var ret bool
		return ret
	}
	return *o.SmtpServerAuthEnabled
}

// GetSmtpServerAuthEnabledOk returns a tuple with the SmtpServerAuthEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetSmtpServerAuthEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.SmtpServerAuthEnabled) {
		return nil, false
	}
	return o.SmtpServerAuthEnabled, true
}

// HasSmtpServerAuthEnabled returns a boolean if a field has been set.
func (o *Settings) HasSmtpServerAuthEnabled() bool {
	if o != nil && !IsNil(o.SmtpServerAuthEnabled) {
		return true
	}

	return false
}

// SetSmtpServerAuthEnabled gets a reference to the given bool and assigns it to the SmtpServerAuthEnabled field.
func (o *Settings) SetSmtpServerAuthEnabled(v bool) {
	o.SmtpServerAuthEnabled = &v
}

// GetSmtpServerEnabled returns the SmtpServerEnabled field value if set, zero value otherwise.
func (o *Settings) GetSmtpServerEnabled() bool {
	if o == nil || IsNil(o.SmtpServerEnabled) {
		var ret bool
		return ret
	}
	return *o.SmtpServerEnabled
}

// GetSmtpServerEnabledOk returns a tuple with the SmtpServerEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetSmtpServerEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.SmtpServerEnabled) {
		return nil, false
	}
	return o.SmtpServerEnabled, true
}

// HasSmtpServerEnabled returns a boolean if a field has been set.
func (o *Settings) HasSmtpServerEnabled() bool {
	if o != nil && !IsNil(o.SmtpServerEnabled) {
		return true
	}

	return false
}

// SetSmtpServerEnabled gets a reference to the given bool and assigns it to the SmtpServerEnabled field.
func (o *Settings) SetSmtpServerEnabled(v bool) {
	o.SmtpServerEnabled = &v
}

// GetSmtpServerHost returns the SmtpServerHost field value if set, zero value otherwise.
func (o *Settings) GetSmtpServerHost() string {
	if o == nil || IsNil(o.SmtpServerHost) {
		var ret string
		return ret
	}
	return *o.SmtpServerHost
}

// GetSmtpServerHostOk returns a tuple with the SmtpServerHost field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetSmtpServerHostOk() (*string, bool) {
	if o == nil || IsNil(o.SmtpServerHost) {
		return nil, false
	}
	return o.SmtpServerHost, true
}

// HasSmtpServerHost returns a boolean if a field has been set.
func (o *Settings) HasSmtpServerHost() bool {
	if o != nil && !IsNil(o.SmtpServerHost) {
		return true
	}

	return false
}

// SetSmtpServerHost gets a reference to the given string and assigns it to the SmtpServerHost field.
func (o *Settings) SetSmtpServerHost(v string) {
	o.SmtpServerHost = &v
}

// GetSmtpServerPassword returns the SmtpServerPassword field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Settings) GetSmtpServerPassword() string {
	if o == nil || IsNil(o.SmtpServerPassword.Get()) {
		var ret string
		return ret
	}
	return *o.SmtpServerPassword.Get()
}

// GetSmtpServerPasswordOk returns a tuple with the SmtpServerPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Settings) GetSmtpServerPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SmtpServerPassword.Get(), o.SmtpServerPassword.IsSet()
}

// HasSmtpServerPassword returns a boolean if a field has been set.
func (o *Settings) HasSmtpServerPassword() bool {
	if o != nil && o.SmtpServerPassword.IsSet() {
		return true
	}

	return false
}

// SetSmtpServerPassword gets a reference to the given NullableString and assigns it to the SmtpServerPassword field.
func (o *Settings) SetSmtpServerPassword(v string) {
	o.SmtpServerPassword.Set(&v)
}
// SetSmtpServerPasswordNil sets the value for SmtpServerPassword to be an explicit nil
func (o *Settings) SetSmtpServerPasswordNil() {
	o.SmtpServerPassword.Set(nil)
}

// UnsetSmtpServerPassword ensures that no value is present for SmtpServerPassword, not even an explicit nil
func (o *Settings) UnsetSmtpServerPassword() {
	o.SmtpServerPassword.Unset()
}

// GetSmtpServerPort returns the SmtpServerPort field value if set, zero value otherwise.
func (o *Settings) GetSmtpServerPort() int32 {
	if o == nil || IsNil(o.SmtpServerPort) {
		var ret int32
		return ret
	}
	return *o.SmtpServerPort
}

// GetSmtpServerPortOk returns a tuple with the SmtpServerPort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetSmtpServerPortOk() (*int32, bool) {
	if o == nil || IsNil(o.SmtpServerPort) {
		return nil, false
	}
	return o.SmtpServerPort, true
}

// HasSmtpServerPort returns a boolean if a field has been set.
func (o *Settings) HasSmtpServerPort() bool {
	if o != nil && !IsNil(o.SmtpServerPort) {
		return true
	}

	return false
}

// SetSmtpServerPort gets a reference to the given int32 and assigns it to the SmtpServerPort field.
func (o *Settings) SetSmtpServerPort(v int32) {
	o.SmtpServerPort = &v
}

// GetSmtpServerProxy returns the SmtpServerProxy field value if set, zero value otherwise.
func (o *Settings) GetSmtpServerProxy() bool {
	if o == nil || IsNil(o.SmtpServerProxy) {
		var ret bool
		return ret
	}
	return *o.SmtpServerProxy
}

// GetSmtpServerProxyOk returns a tuple with the SmtpServerProxy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetSmtpServerProxyOk() (*bool, bool) {
	if o == nil || IsNil(o.SmtpServerProxy) {
		return nil, false
	}
	return o.SmtpServerProxy, true
}

// HasSmtpServerProxy returns a boolean if a field has been set.
func (o *Settings) HasSmtpServerProxy() bool {
	if o != nil && !IsNil(o.SmtpServerProxy) {
		return true
	}

	return false
}

// SetSmtpServerProxy gets a reference to the given bool and assigns it to the SmtpServerProxy field.
func (o *Settings) SetSmtpServerProxy(v bool) {
	o.SmtpServerProxy = &v
}

// GetSmtpServerTLSEnabled returns the SmtpServerTLSEnabled field value if set, zero value otherwise.
func (o *Settings) GetSmtpServerTLSEnabled() bool {
	if o == nil || IsNil(o.SmtpServerTLSEnabled) {
		var ret bool
		return ret
	}
	return *o.SmtpServerTLSEnabled
}

// GetSmtpServerTLSEnabledOk returns a tuple with the SmtpServerTLSEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetSmtpServerTLSEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.SmtpServerTLSEnabled) {
		return nil, false
	}
	return o.SmtpServerTLSEnabled, true
}

// HasSmtpServerTLSEnabled returns a boolean if a field has been set.
func (o *Settings) HasSmtpServerTLSEnabled() bool {
	if o != nil && !IsNil(o.SmtpServerTLSEnabled) {
		return true
	}

	return false
}

// SetSmtpServerTLSEnabled gets a reference to the given bool and assigns it to the SmtpServerTLSEnabled field.
func (o *Settings) SetSmtpServerTLSEnabled(v bool) {
	o.SmtpServerTLSEnabled = &v
}

// GetSmtpStrategy returns the SmtpStrategy field value if set, zero value otherwise.
func (o *Settings) GetSmtpStrategy() SmtpStrategy {
	if o == nil || IsNil(o.SmtpStrategy) {
		var ret SmtpStrategy
		return ret
	}
	return *o.SmtpStrategy
}

// GetSmtpStrategyOk returns a tuple with the SmtpStrategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetSmtpStrategyOk() (*SmtpStrategy, bool) {
	if o == nil || IsNil(o.SmtpStrategy) {
		return nil, false
	}
	return o.SmtpStrategy, true
}

// HasSmtpStrategy returns a boolean if a field has been set.
func (o *Settings) HasSmtpStrategy() bool {
	if o != nil && !IsNil(o.SmtpStrategy) {
		return true
	}

	return false
}

// SetSmtpStrategy gets a reference to the given SmtpStrategy and assigns it to the SmtpStrategy field.
func (o *Settings) SetSmtpStrategy(v SmtpStrategy) {
	o.SmtpStrategy = &v
}

// GetTemplateHeader returns the TemplateHeader field value if set, zero value otherwise.
func (o *Settings) GetTemplateHeader() string {
	if o == nil || IsNil(o.TemplateHeader) {
		var ret string
		return ret
	}
	return *o.TemplateHeader
}

// GetTemplateHeaderOk returns a tuple with the TemplateHeader field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetTemplateHeaderOk() (*string, bool) {
	if o == nil || IsNil(o.TemplateHeader) {
		return nil, false
	}
	return o.TemplateHeader, true
}

// HasTemplateHeader returns a boolean if a field has been set.
func (o *Settings) HasTemplateHeader() bool {
	if o != nil && !IsNil(o.TemplateHeader) {
		return true
	}

	return false
}

// SetTemplateHeader gets a reference to the given string and assigns it to the TemplateHeader field.
func (o *Settings) SetTemplateHeader(v string) {
	o.TemplateHeader = &v
}

// GetTemplateHtmlHead returns the TemplateHtmlHead field value if set, zero value otherwise.
func (o *Settings) GetTemplateHtmlHead() string {
	if o == nil || IsNil(o.TemplateHtmlHead) {
		var ret string
		return ret
	}
	return *o.TemplateHtmlHead
}

// GetTemplateHtmlHeadOk returns a tuple with the TemplateHtmlHead field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetTemplateHtmlHeadOk() (*string, bool) {
	if o == nil || IsNil(o.TemplateHtmlHead) {
		return nil, false
	}
	return o.TemplateHtmlHead, true
}

// HasTemplateHtmlHead returns a boolean if a field has been set.
func (o *Settings) HasTemplateHtmlHead() bool {
	if o != nil && !IsNil(o.TemplateHtmlHead) {
		return true
	}

	return false
}

// SetTemplateHtmlHead gets a reference to the given string and assigns it to the TemplateHtmlHead field.
func (o *Settings) SetTemplateHtmlHead(v string) {
	o.TemplateHtmlHead = &v
}

// GetTimezone returns the Timezone field value if set, zero value otherwise.
func (o *Settings) GetTimezone() string {
	if o == nil || IsNil(o.Timezone) {
		var ret string
		return ret
	}
	return *o.Timezone
}

// GetTimezoneOk returns a tuple with the Timezone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetTimezoneOk() (*string, bool) {
	if o == nil || IsNil(o.Timezone) {
		return nil, false
	}
	return o.Timezone, true
}

// HasTimezone returns a boolean if a field has been set.
func (o *Settings) HasTimezone() bool {
	if o != nil && !IsNil(o.Timezone) {
		return true
	}

	return false
}

// SetTimezone gets a reference to the given string and assigns it to the Timezone field.
func (o *Settings) SetTimezone(v string) {
	o.Timezone = &v
}

// GetTrackClicks returns the TrackClicks field value if set, zero value otherwise.
func (o *Settings) GetTrackClicks() bool {
	if o == nil || IsNil(o.TrackClicks) {
		var ret bool
		return ret
	}
	return *o.TrackClicks
}

// GetTrackClicksOk returns a tuple with the TrackClicks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetTrackClicksOk() (*bool, bool) {
	if o == nil || IsNil(o.TrackClicks) {
		return nil, false
	}
	return o.TrackClicks, true
}

// HasTrackClicks returns a boolean if a field has been set.
func (o *Settings) HasTrackClicks() bool {
	if o != nil && !IsNil(o.TrackClicks) {
		return true
	}

	return false
}

// SetTrackClicks gets a reference to the given bool and assigns it to the TrackClicks field.
func (o *Settings) SetTrackClicks(v bool) {
	o.TrackClicks = &v
}

// GetTrackOpens returns the TrackOpens field value if set, zero value otherwise.
func (o *Settings) GetTrackOpens() bool {
	if o == nil || IsNil(o.TrackOpens) {
		var ret bool
		return ret
	}
	return *o.TrackOpens
}

// GetTrackOpensOk returns a tuple with the TrackOpens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetTrackOpensOk() (*bool, bool) {
	if o == nil || IsNil(o.TrackOpens) {
		return nil, false
	}
	return o.TrackOpens, true
}

// HasTrackOpens returns a boolean if a field has been set.
func (o *Settings) HasTrackOpens() bool {
	if o != nil && !IsNil(o.TrackOpens) {
		return true
	}

	return false
}

// SetTrackOpens gets a reference to the given bool and assigns it to the TrackOpens field.
func (o *Settings) SetTrackOpens(v bool) {
	o.TrackOpens = &v
}

// GetWebhookEvents returns the WebhookEvents field value if set, zero value otherwise.
func (o *Settings) GetWebhookEvents() []string {
	if o == nil || IsNil(o.WebhookEvents) {
		var ret []string
		return ret
	}
	return o.WebhookEvents
}

// GetWebhookEventsOk returns a tuple with the WebhookEvents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetWebhookEventsOk() ([]string, bool) {
	if o == nil || IsNil(o.WebhookEvents) {
		return nil, false
	}
	return o.WebhookEvents, true
}

// HasWebhookEvents returns a boolean if a field has been set.
func (o *Settings) HasWebhookEvents() bool {
	if o != nil && !IsNil(o.WebhookEvents) {
		return true
	}

	return false
}

// SetWebhookEvents gets a reference to the given []string and assigns it to the WebhookEvents field.
func (o *Settings) SetWebhookEvents(v []string) {
	o.WebhookEvents = v
}

// GetWebhooks returns the Webhooks field value if set, zero value otherwise.
func (o *Settings) GetWebhooks() string {
	if o == nil || IsNil(o.Webhooks) {
		var ret string
		return ret
	}
	return *o.Webhooks
}

// GetWebhooksOk returns a tuple with the Webhooks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetWebhooksOk() (*string, bool) {
	if o == nil || IsNil(o.Webhooks) {
		return nil, false
	}
	return o.Webhooks, true
}

// HasWebhooks returns a boolean if a field has been set.
func (o *Settings) HasWebhooks() bool {
	if o != nil && !IsNil(o.Webhooks) {
		return true
	}

	return false
}

// SetWebhooks gets a reference to the given string and assigns it to the Webhooks field.
func (o *Settings) SetWebhooks(v string) {
	o.Webhooks = &v
}

// GetWebhooksCustomHeaders returns the WebhooksCustomHeaders field value if set, zero value otherwise.
func (o *Settings) GetWebhooksCustomHeaders() []WebhooksCustomHeader {
	if o == nil || IsNil(o.WebhooksCustomHeaders) {
		var ret []WebhooksCustomHeader
		return ret
	}
	return o.WebhooksCustomHeaders
}

// GetWebhooksCustomHeadersOk returns a tuple with the WebhooksCustomHeaders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetWebhooksCustomHeadersOk() ([]WebhooksCustomHeader, bool) {
	if o == nil || IsNil(o.WebhooksCustomHeaders) {
		return nil, false
	}
	return o.WebhooksCustomHeaders, true
}

// HasWebhooksCustomHeaders returns a boolean if a field has been set.
func (o *Settings) HasWebhooksCustomHeaders() bool {
	if o != nil && !IsNil(o.WebhooksCustomHeaders) {
		return true
	}

	return false
}

// SetWebhooksCustomHeaders gets a reference to the given []WebhooksCustomHeader and assigns it to the WebhooksCustomHeaders field.
func (o *Settings) SetWebhooksCustomHeaders(v []WebhooksCustomHeader) {
	o.WebhooksCustomHeaders = v
}

// GetWebhooksEnabled returns the WebhooksEnabled field value if set, zero value otherwise.
func (o *Settings) GetWebhooksEnabled() bool {
	if o == nil || IsNil(o.WebhooksEnabled) {
		var ret bool
		return ret
	}
	return *o.WebhooksEnabled
}

// GetWebhooksEnabledOk returns a tuple with the WebhooksEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Settings) GetWebhooksEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.WebhooksEnabled) {
		return nil, false
	}
	return o.WebhooksEnabled, true
}

// HasWebhooksEnabled returns a boolean if a field has been set.
func (o *Settings) HasWebhooksEnabled() bool {
	if o != nil && !IsNil(o.WebhooksEnabled) {
		return true
	}

	return false
}

// SetWebhooksEnabled gets a reference to the given bool and assigns it to the WebhooksEnabled field.
func (o *Settings) SetWebhooksEnabled(v bool) {
	o.WebhooksEnabled = &v
}

func (o Settings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Settings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AuthServer) {
		toSerialize["authServer"] = o.AuthServer
	}
	if !IsNil(o.DeliveryAttempts) {
		toSerialize["deliveryAttempts"] = o.DeliveryAttempts
	}
	if !IsNil(o.EnableApiProxy) {
		toSerialize["enableApiProxy"] = o.EnableApiProxy
	}
	if !IsNil(o.GenerateEmailSummary) {
		toSerialize["generateEmailSummary"] = o.GenerateEmailSummary
	}
	if !IsNil(o.IgnoreMailCertErrors) {
		toSerialize["ignoreMailCertErrors"] = o.IgnoreMailCertErrors
	}
	if !IsNil(o.ImapClientName) {
		toSerialize["imapClientName"] = o.ImapClientName
	}
	if !IsNil(o.ImapClientSupportUrl) {
		toSerialize["imapClientSupportUrl"] = o.ImapClientSupportUrl
	}
	if !IsNil(o.ImapClientVendor) {
		toSerialize["imapClientVendor"] = o.ImapClientVendor
	}
	if !IsNil(o.ImapClientVersion) {
		toSerialize["imapClientVersion"] = o.ImapClientVersion
	}
	if !IsNil(o.ImapIndexer) {
		toSerialize["imapIndexer"] = o.ImapIndexer
	}
	if !IsNil(o.ImapProxyServerEnabled) {
		toSerialize["imapProxyServerEnabled"] = o.ImapProxyServerEnabled
	}
	if !IsNil(o.ImapProxyServerHost) {
		toSerialize["imapProxyServerHost"] = o.ImapProxyServerHost
	}
	if o.ImapProxyServerPassword.IsSet() {
		toSerialize["imapProxyServerPassword"] = o.ImapProxyServerPassword.Get()
	}
	if !IsNil(o.ImapProxyServerPort) {
		toSerialize["imapProxyServerPort"] = o.ImapProxyServerPort
	}
	if !IsNil(o.ImapProxyServerProxy) {
		toSerialize["imapProxyServerProxy"] = o.ImapProxyServerProxy
	}
	if !IsNil(o.ImapProxyServerTLSEnabled) {
		toSerialize["imapProxyServerTLSEnabled"] = o.ImapProxyServerTLSEnabled
	}
	if !IsNil(o.ImapStrategy) {
		toSerialize["imapStrategy"] = o.ImapStrategy
	}
	if !IsNil(o.InboxNewOnly) {
		toSerialize["inboxNewOnly"] = o.InboxNewOnly
	}
	if !IsNil(o.LocalAddresses) {
		toSerialize["localAddresses"] = o.LocalAddresses
	}
	if !IsNil(o.Locale) {
		toSerialize["locale"] = o.Locale
	}
	if !IsNil(o.Logs) {
		toSerialize["logs"] = o.Logs
	}
	if o.NotificationBaseUrl.IsSet() {
		toSerialize["notificationBaseUrl"] = o.NotificationBaseUrl.Get()
	}
	if !IsNil(o.NotifyAttachmentSize) {
		toSerialize["notifyAttachmentSize"] = o.NotifyAttachmentSize
	}
	if !IsNil(o.NotifyAttachments) {
		toSerialize["notifyAttachments"] = o.NotifyAttachments
	}
	if !IsNil(o.NotifyCalendarEvents) {
		toSerialize["notifyCalendarEvents"] = o.NotifyCalendarEvents
	}
	if !IsNil(o.NotifyHeaders) {
		toSerialize["notifyHeaders"] = o.NotifyHeaders
	}
	if !IsNil(o.NotifyText) {
		toSerialize["notifyText"] = o.NotifyText
	}
	if !IsNil(o.NotifyTextSize) {
		toSerialize["notifyTextSize"] = o.NotifyTextSize
	}
	if !IsNil(o.NotifyWebSafeHtml) {
		toSerialize["notifyWebSafeHtml"] = o.NotifyWebSafeHtml
	}
	if !IsNil(o.OpenAiAPIKey) {
		toSerialize["openAiAPIKey"] = o.OpenAiAPIKey
	}
	if !IsNil(o.OpenAiAPIUrl) {
		toSerialize["openAiAPIUrl"] = o.OpenAiAPIUrl
	}
	if !IsNil(o.OpenAiGenerateEmbeddings) {
		toSerialize["openAiGenerateEmbeddings"] = o.OpenAiGenerateEmbeddings
	}
	if !IsNil(o.OpenAiMaxTokens) {
		toSerialize["openAiMaxTokens"] = o.OpenAiMaxTokens
	}
	if !IsNil(o.OpenAiModel) {
		toSerialize["openAiModel"] = o.OpenAiModel
	}
	if !IsNil(o.OpenAiPreProcessingFn) {
		toSerialize["openAiPreProcessingFn"] = o.OpenAiPreProcessingFn
	}
	if !IsNil(o.OpenAiPrompt) {
		toSerialize["openAiPrompt"] = o.OpenAiPrompt
	}
	if !IsNil(o.OpenAiTemperature) {
		toSerialize["openAiTemperature"] = o.OpenAiTemperature
	}
	if !IsNil(o.OpenAiTopP) {
		toSerialize["openAiTopP"] = o.OpenAiTopP
	}
	if o.PageBrandName.IsSet() {
		toSerialize["pageBrandName"] = o.PageBrandName.Get()
	}
	if !IsNil(o.ProxyEnabled) {
		toSerialize["proxyEnabled"] = o.ProxyEnabled
	}
	if !IsNil(o.ProxyUrl) {
		toSerialize["proxyUrl"] = o.ProxyUrl
	}
	if !IsNil(o.QueueKeep) {
		toSerialize["queueKeep"] = o.QueueKeep
	}
	if !IsNil(o.ResolveGmailCategories) {
		toSerialize["resolveGmailCategories"] = o.ResolveGmailCategories
	}
	if !IsNil(o.ScriptEnv) {
		toSerialize["scriptEnv"] = o.ScriptEnv
	}
	if !IsNil(o.ServiceSecret) {
		toSerialize["serviceSecret"] = o.ServiceSecret
	}
	if !IsNil(o.ServiceUrl) {
		toSerialize["serviceUrl"] = o.ServiceUrl
	}
	if o.SmtpEhloName.IsSet() {
		toSerialize["smtpEhloName"] = o.SmtpEhloName.Get()
	}
	if !IsNil(o.SmtpServerAuthEnabled) {
		toSerialize["smtpServerAuthEnabled"] = o.SmtpServerAuthEnabled
	}
	if !IsNil(o.SmtpServerEnabled) {
		toSerialize["smtpServerEnabled"] = o.SmtpServerEnabled
	}
	if !IsNil(o.SmtpServerHost) {
		toSerialize["smtpServerHost"] = o.SmtpServerHost
	}
	if o.SmtpServerPassword.IsSet() {
		toSerialize["smtpServerPassword"] = o.SmtpServerPassword.Get()
	}
	if !IsNil(o.SmtpServerPort) {
		toSerialize["smtpServerPort"] = o.SmtpServerPort
	}
	if !IsNil(o.SmtpServerProxy) {
		toSerialize["smtpServerProxy"] = o.SmtpServerProxy
	}
	if !IsNil(o.SmtpServerTLSEnabled) {
		toSerialize["smtpServerTLSEnabled"] = o.SmtpServerTLSEnabled
	}
	if !IsNil(o.SmtpStrategy) {
		toSerialize["smtpStrategy"] = o.SmtpStrategy
	}
	if !IsNil(o.TemplateHeader) {
		toSerialize["templateHeader"] = o.TemplateHeader
	}
	if !IsNil(o.TemplateHtmlHead) {
		toSerialize["templateHtmlHead"] = o.TemplateHtmlHead
	}
	if !IsNil(o.Timezone) {
		toSerialize["timezone"] = o.Timezone
	}
	if !IsNil(o.TrackClicks) {
		toSerialize["trackClicks"] = o.TrackClicks
	}
	if !IsNil(o.TrackOpens) {
		toSerialize["trackOpens"] = o.TrackOpens
	}
	if !IsNil(o.WebhookEvents) {
		toSerialize["webhookEvents"] = o.WebhookEvents
	}
	if !IsNil(o.Webhooks) {
		toSerialize["webhooks"] = o.Webhooks
	}
	if !IsNil(o.WebhooksCustomHeaders) {
		toSerialize["webhooksCustomHeaders"] = o.WebhooksCustomHeaders
	}
	if !IsNil(o.WebhooksEnabled) {
		toSerialize["webhooksEnabled"] = o.WebhooksEnabled
	}
	return toSerialize, nil
}

type NullableSettings struct {
	value *Settings
	isSet bool
}

func (v NullableSettings) Get() *Settings {
	return v.value
}

func (v *NullableSettings) Set(val *Settings) {
	v.value = val
	v.isSet = true
}

func (v NullableSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettings(val *Settings) *NullableSettings {
	return &NullableSettings{value: val, isSet: true}
}

func (v NullableSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


