/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the TemplateRender type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateRender{}

// TemplateRender Template rendering options
type TemplateRender struct {
	Format *Format `json:"format,omitempty"`
	// An object of variables for the template renderer
	Params map[string]interface{} `json:"params,omitempty"`
}

// NewTemplateRender instantiates a new TemplateRender object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateRender() *TemplateRender {
	this := TemplateRender{}
	var format Format = FORMAT_HTML
	this.Format = &format
	return &this
}

// NewTemplateRenderWithDefaults instantiates a new TemplateRender object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateRenderWithDefaults() *TemplateRender {
	this := TemplateRender{}
	var format Format = FORMAT_HTML
	this.Format = &format
	return &this
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *TemplateRender) GetFormat() Format {
	if o == nil || IsNil(o.Format) {
		var ret Format
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateRender) GetFormatOk() (*Format, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *TemplateRender) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given Format and assigns it to the Format field.
func (o *TemplateRender) SetFormat(v Format) {
	o.Format = &v
}

// GetParams returns the Params field value if set, zero value otherwise.
func (o *TemplateRender) GetParams() map[string]interface{} {
	if o == nil || IsNil(o.Params) {
		var ret map[string]interface{}
		return ret
	}
	return o.Params
}

// GetParamsOk returns a tuple with the Params field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateRender) GetParamsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Params) {
		return map[string]interface{}{}, false
	}
	return o.Params, true
}

// HasParams returns a boolean if a field has been set.
func (o *TemplateRender) HasParams() bool {
	if o != nil && !IsNil(o.Params) {
		return true
	}

	return false
}

// SetParams gets a reference to the given map[string]interface{} and assigns it to the Params field.
func (o *TemplateRender) SetParams(v map[string]interface{}) {
	o.Params = v
}

func (o TemplateRender) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateRender) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	if !IsNil(o.Params) {
		toSerialize["params"] = o.Params
	}
	return toSerialize, nil
}

type NullableTemplateRender struct {
	value *TemplateRender
	isSet bool
}

func (v NullableTemplateRender) Get() *TemplateRender {
	return v.value
}

func (v *NullableTemplateRender) Set(val *TemplateRender) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateRender) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateRender) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateRender(val *TemplateRender) *NullableTemplateRender {
	return &NullableTemplateRender{value: val, isSet: true}
}

func (v NullableTemplateRender) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateRender) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


