/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MailboxShortResponseItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailboxShortResponseItem{}

// MailboxShortResponseItem struct for MailboxShortResponseItem
type MailboxShortResponseItem struct {
	// Hierarchy delimiter character used in paths
	Delimiter *string `json:"delimiter,omitempty"`
	// Whether this mailbox appears in LIST command results
	Listed *bool `json:"listed,omitempty"`
	// Display name of the mailbox
	Name string `json:"name"`
	// Path to the parent mailbox
	ParentPath string `json:"parentPath"`
	// Full path to the mailbox
	Path string `json:"path"`
	SpecialUse *MailboxSpecialUse `json:"specialUse,omitempty"`
	// Whether the user is subscribed to this mailbox
	Subscribed *bool `json:"subscribed,omitempty"`
}

type _MailboxShortResponseItem MailboxShortResponseItem

// NewMailboxShortResponseItem instantiates a new MailboxShortResponseItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailboxShortResponseItem(name string, parentPath string, path string) *MailboxShortResponseItem {
	this := MailboxShortResponseItem{}
	this.Name = name
	this.ParentPath = parentPath
	this.Path = path
	return &this
}

// NewMailboxShortResponseItemWithDefaults instantiates a new MailboxShortResponseItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailboxShortResponseItemWithDefaults() *MailboxShortResponseItem {
	this := MailboxShortResponseItem{}
	return &this
}

// GetDelimiter returns the Delimiter field value if set, zero value otherwise.
func (o *MailboxShortResponseItem) GetDelimiter() string {
	if o == nil || IsNil(o.Delimiter) {
		var ret string
		return ret
	}
	return *o.Delimiter
}

// GetDelimiterOk returns a tuple with the Delimiter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MailboxShortResponseItem) GetDelimiterOk() (*string, bool) {
	if o == nil || IsNil(o.Delimiter) {
		return nil, false
	}
	return o.Delimiter, true
}

// HasDelimiter returns a boolean if a field has been set.
func (o *MailboxShortResponseItem) HasDelimiter() bool {
	if o != nil && !IsNil(o.Delimiter) {
		return true
	}

	return false
}

// SetDelimiter gets a reference to the given string and assigns it to the Delimiter field.
func (o *MailboxShortResponseItem) SetDelimiter(v string) {
	o.Delimiter = &v
}

// GetListed returns the Listed field value if set, zero value otherwise.
func (o *MailboxShortResponseItem) GetListed() bool {
	if o == nil || IsNil(o.Listed) {
		var ret bool
		return ret
	}
	return *o.Listed
}

// GetListedOk returns a tuple with the Listed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MailboxShortResponseItem) GetListedOk() (*bool, bool) {
	if o == nil || IsNil(o.Listed) {
		return nil, false
	}
	return o.Listed, true
}

// HasListed returns a boolean if a field has been set.
func (o *MailboxShortResponseItem) HasListed() bool {
	if o != nil && !IsNil(o.Listed) {
		return true
	}

	return false
}

// SetListed gets a reference to the given bool and assigns it to the Listed field.
func (o *MailboxShortResponseItem) SetListed(v bool) {
	o.Listed = &v
}

// GetName returns the Name field value
func (o *MailboxShortResponseItem) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *MailboxShortResponseItem) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *MailboxShortResponseItem) SetName(v string) {
	o.Name = v
}

// GetParentPath returns the ParentPath field value
func (o *MailboxShortResponseItem) GetParentPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ParentPath
}

// GetParentPathOk returns a tuple with the ParentPath field value
// and a boolean to check if the value has been set.
func (o *MailboxShortResponseItem) GetParentPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ParentPath, true
}

// SetParentPath sets field value
func (o *MailboxShortResponseItem) SetParentPath(v string) {
	o.ParentPath = v
}

// GetPath returns the Path field value
func (o *MailboxShortResponseItem) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *MailboxShortResponseItem) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *MailboxShortResponseItem) SetPath(v string) {
	o.Path = v
}

// GetSpecialUse returns the SpecialUse field value if set, zero value otherwise.
func (o *MailboxShortResponseItem) GetSpecialUse() MailboxSpecialUse {
	if o == nil || IsNil(o.SpecialUse) {
		var ret MailboxSpecialUse
		return ret
	}
	return *o.SpecialUse
}

// GetSpecialUseOk returns a tuple with the SpecialUse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MailboxShortResponseItem) GetSpecialUseOk() (*MailboxSpecialUse, bool) {
	if o == nil || IsNil(o.SpecialUse) {
		return nil, false
	}
	return o.SpecialUse, true
}

// HasSpecialUse returns a boolean if a field has been set.
func (o *MailboxShortResponseItem) HasSpecialUse() bool {
	if o != nil && !IsNil(o.SpecialUse) {
		return true
	}

	return false
}

// SetSpecialUse gets a reference to the given MailboxSpecialUse and assigns it to the SpecialUse field.
func (o *MailboxShortResponseItem) SetSpecialUse(v MailboxSpecialUse) {
	o.SpecialUse = &v
}

// GetSubscribed returns the Subscribed field value if set, zero value otherwise.
func (o *MailboxShortResponseItem) GetSubscribed() bool {
	if o == nil || IsNil(o.Subscribed) {
		var ret bool
		return ret
	}
	return *o.Subscribed
}

// GetSubscribedOk returns a tuple with the Subscribed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MailboxShortResponseItem) GetSubscribedOk() (*bool, bool) {
	if o == nil || IsNil(o.Subscribed) {
		return nil, false
	}
	return o.Subscribed, true
}

// HasSubscribed returns a boolean if a field has been set.
func (o *MailboxShortResponseItem) HasSubscribed() bool {
	if o != nil && !IsNil(o.Subscribed) {
		return true
	}

	return false
}

// SetSubscribed gets a reference to the given bool and assigns it to the Subscribed field.
func (o *MailboxShortResponseItem) SetSubscribed(v bool) {
	o.Subscribed = &v
}

func (o MailboxShortResponseItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailboxShortResponseItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Delimiter) {
		toSerialize["delimiter"] = o.Delimiter
	}
	if !IsNil(o.Listed) {
		toSerialize["listed"] = o.Listed
	}
	toSerialize["name"] = o.Name
	toSerialize["parentPath"] = o.ParentPath
	toSerialize["path"] = o.Path
	if !IsNil(o.SpecialUse) {
		toSerialize["specialUse"] = o.SpecialUse
	}
	if !IsNil(o.Subscribed) {
		toSerialize["subscribed"] = o.Subscribed
	}
	return toSerialize, nil
}

func (o *MailboxShortResponseItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"parentPath",
		"path",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailboxShortResponseItem := _MailboxShortResponseItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMailboxShortResponseItem)

	if err != nil {
		return err
	}

	*o = MailboxShortResponseItem(varMailboxShortResponseItem)

	return err
}

type NullableMailboxShortResponseItem struct {
	value *MailboxShortResponseItem
	isSet bool
}

func (v NullableMailboxShortResponseItem) Get() *MailboxShortResponseItem {
	return v.value
}

func (v *NullableMailboxShortResponseItem) Set(val *MailboxShortResponseItem) {
	v.value = val
	v.isSet = true
}

func (v NullableMailboxShortResponseItem) IsSet() bool {
	return v.isSet
}

func (v *NullableMailboxShortResponseItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailboxShortResponseItem(val *MailboxShortResponseItem) *NullableMailboxShortResponseItem {
	return &NullableMailboxShortResponseItem{value: val, isSet: true}
}

func (v NullableMailboxShortResponseItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailboxShortResponseItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


