/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the RequestReconnectResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestReconnectResponse{}

// RequestReconnectResponse struct for RequestReconnectResponse
type RequestReconnectResponse struct {
	// Reconnection status
	Reconnect *bool `json:"reconnect,omitempty"`
}

// NewRequestReconnectResponse instantiates a new RequestReconnectResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestReconnectResponse() *RequestReconnectResponse {
	this := RequestReconnectResponse{}
	var reconnect bool = false
	this.Reconnect = &reconnect
	return &this
}

// NewRequestReconnectResponseWithDefaults instantiates a new RequestReconnectResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestReconnectResponseWithDefaults() *RequestReconnectResponse {
	this := RequestReconnectResponse{}
	var reconnect bool = false
	this.Reconnect = &reconnect
	return &this
}

// GetReconnect returns the Reconnect field value if set, zero value otherwise.
func (o *RequestReconnectResponse) GetReconnect() bool {
	if o == nil || IsNil(o.Reconnect) {
		var ret bool
		return ret
	}
	return *o.Reconnect
}

// GetReconnectOk returns a tuple with the Reconnect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RequestReconnectResponse) GetReconnectOk() (*bool, bool) {
	if o == nil || IsNil(o.Reconnect) {
		return nil, false
	}
	return o.Reconnect, true
}

// HasReconnect returns a boolean if a field has been set.
func (o *RequestReconnectResponse) HasReconnect() bool {
	if o != nil && !IsNil(o.Reconnect) {
		return true
	}

	return false
}

// SetReconnect gets a reference to the given bool and assigns it to the Reconnect field.
func (o *RequestReconnectResponse) SetReconnect(v bool) {
	o.Reconnect = &v
}

func (o RequestReconnectResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestReconnectResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Reconnect) {
		toSerialize["reconnect"] = o.Reconnect
	}
	return toSerialize, nil
}

type NullableRequestReconnectResponse struct {
	value *RequestReconnectResponse
	isSet bool
}

func (v NullableRequestReconnectResponse) Get() *RequestReconnectResponse {
	return v.value
}

func (v *NullableRequestReconnectResponse) Set(val *RequestReconnectResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestReconnectResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestReconnectResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestReconnectResponse(val *RequestReconnectResponse) *NullableRequestReconnectResponse {
	return &NullableRequestReconnectResponse{value: val, isSet: true}
}

func (v NullableRequestReconnectResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestReconnectResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


