/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the TextInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TextInfo{}

// TextInfo struct for TextInfo
type TextInfo struct {
	EncodedSize *EncodedSize `json:"encodedSize,omitempty"`
	// Identifier for fetching the full message text
	Id *string `json:"id,omitempty"`
}

// NewTextInfo instantiates a new TextInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTextInfo() *TextInfo {
	this := TextInfo{}
	return &this
}

// NewTextInfoWithDefaults instantiates a new TextInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTextInfoWithDefaults() *TextInfo {
	this := TextInfo{}
	return &this
}

// GetEncodedSize returns the EncodedSize field value if set, zero value otherwise.
func (o *TextInfo) GetEncodedSize() EncodedSize {
	if o == nil || IsNil(o.EncodedSize) {
		var ret EncodedSize
		return ret
	}
	return *o.EncodedSize
}

// GetEncodedSizeOk returns a tuple with the EncodedSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextInfo) GetEncodedSizeOk() (*EncodedSize, bool) {
	if o == nil || IsNil(o.EncodedSize) {
		return nil, false
	}
	return o.EncodedSize, true
}

// HasEncodedSize returns a boolean if a field has been set.
func (o *TextInfo) HasEncodedSize() bool {
	if o != nil && !IsNil(o.EncodedSize) {
		return true
	}

	return false
}

// SetEncodedSize gets a reference to the given EncodedSize and assigns it to the EncodedSize field.
func (o *TextInfo) SetEncodedSize(v EncodedSize) {
	o.EncodedSize = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TextInfo) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextInfo) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TextInfo) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TextInfo) SetId(v string) {
	o.Id = &v
}

func (o TextInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TextInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EncodedSize) {
		toSerialize["encodedSize"] = o.EncodedSize
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableTextInfo struct {
	value *TextInfo
	isSet bool
}

func (v NullableTextInfo) Get() *TextInfo {
	return v.value
}

func (v *NullableTextInfo) Set(val *TextInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableTextInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableTextInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTextInfo(val *TextInfo) *NullableTextInfo {
	return &NullableTextInfo{value: val, isSet: true}
}

func (v NullableTextInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTextInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


