/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// OAuth2Provider OAuth2 provider
type OAuth2Provider string

// List of OAuth2Provider
const (
	OAUTH2PROVIDER_GMAIL OAuth2Provider = "gmail"
	OAUTH2PROVIDER_GMAIL_SERVICE OAuth2Provider = "gmailService"
	OAUTH2PROVIDER_OUTLOOK OAuth2Provider = "outlook"
	OAUTH2PROVIDER_MAIL_RU OAuth2Provider = "mailRu"
)

// All allowed values of OAuth2Provider enum
var AllowedOAuth2ProviderEnumValues = []OAuth2Provider{
	"gmail",
	"gmailService",
	"outlook",
	"mailRu",
}

func (v *OAuth2Provider) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := OAuth2Provider(value)
	for _, existing := range AllowedOAuth2ProviderEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid OAuth2Provider", value)
}

// NewOAuth2ProviderFromValue returns a pointer to a valid OAuth2Provider
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewOAuth2ProviderFromValue(v string) (*OAuth2Provider, error) {
	ev := OAuth2Provider(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for OAuth2Provider: valid values are %v", v, AllowedOAuth2ProviderEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v OAuth2Provider) IsValid() bool {
	for _, existing := range AllowedOAuth2ProviderEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to OAuth2Provider value
func (v OAuth2Provider) Ptr() *OAuth2Provider {
	return &v
}

type NullableOAuth2Provider struct {
	value *OAuth2Provider
	isSet bool
}

func (v NullableOAuth2Provider) Get() *OAuth2Provider {
	return v.value
}

func (v *NullableOAuth2Provider) Set(val *OAuth2Provider) {
	v.value = val
	v.isSet = true
}

func (v NullableOAuth2Provider) IsSet() bool {
	return v.isSet
}

func (v *NullableOAuth2Provider) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOAuth2Provider(val *OAuth2Provider) *NullableOAuth2Provider {
	return &NullableOAuth2Provider{value: val, isSet: true}
}

func (v NullableOAuth2Provider) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOAuth2Provider) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

