/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the BlocklistListAddResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlocklistListAddResponse{}

// BlocklistListAddResponse struct for BlocklistListAddResponse
type BlocklistListAddResponse struct {
	// Was the address added to the list
	Added *bool `json:"added,omitempty"`
	// Was the request successful
	Success *bool `json:"success,omitempty"`
}

// NewBlocklistListAddResponse instantiates a new BlocklistListAddResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlocklistListAddResponse() *BlocklistListAddResponse {
	this := BlocklistListAddResponse{}
	return &this
}

// NewBlocklistListAddResponseWithDefaults instantiates a new BlocklistListAddResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlocklistListAddResponseWithDefaults() *BlocklistListAddResponse {
	this := BlocklistListAddResponse{}
	return &this
}

// GetAdded returns the Added field value if set, zero value otherwise.
func (o *BlocklistListAddResponse) GetAdded() bool {
	if o == nil || IsNil(o.Added) {
		var ret bool
		return ret
	}
	return *o.Added
}

// GetAddedOk returns a tuple with the Added field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlocklistListAddResponse) GetAddedOk() (*bool, bool) {
	if o == nil || IsNil(o.Added) {
		return nil, false
	}
	return o.Added, true
}

// HasAdded returns a boolean if a field has been set.
func (o *BlocklistListAddResponse) HasAdded() bool {
	if o != nil && !IsNil(o.Added) {
		return true
	}

	return false
}

// SetAdded gets a reference to the given bool and assigns it to the Added field.
func (o *BlocklistListAddResponse) SetAdded(v bool) {
	o.Added = &v
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *BlocklistListAddResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlocklistListAddResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *BlocklistListAddResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *BlocklistListAddResponse) SetSuccess(v bool) {
	o.Success = &v
}

func (o BlocklistListAddResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlocklistListAddResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Added) {
		toSerialize["added"] = o.Added
	}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	return toSerialize, nil
}

type NullableBlocklistListAddResponse struct {
	value *BlocklistListAddResponse
	isSet bool
}

func (v NullableBlocklistListAddResponse) Get() *BlocklistListAddResponse {
	return v.value
}

func (v *NullableBlocklistListAddResponse) Set(val *BlocklistListAddResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBlocklistListAddResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBlocklistListAddResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlocklistListAddResponse(val *BlocklistListAddResponse) *NullableBlocklistListAddResponse {
	return &NullableBlocklistListAddResponse{value: val, isSet: true}
}

func (v NullableBlocklistListAddResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlocklistListAddResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


