/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteAppRequestResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteAppRequestResponse{}

// DeleteAppRequestResponse struct for DeleteAppRequestResponse
type DeleteAppRequestResponse struct {
	// The number of accounts registered with this application. Not available for legacy apps.
	Accounts *int32 `json:"accounts,omitempty"`
	// Was the OAuth2 application deleted
	Deleted *bool `json:"deleted,omitempty"`
	// OAuth2 application ID
	Id string `json:"id"`
}

type _DeleteAppRequestResponse DeleteAppRequestResponse

// NewDeleteAppRequestResponse instantiates a new DeleteAppRequestResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteAppRequestResponse(id string) *DeleteAppRequestResponse {
	this := DeleteAppRequestResponse{}
	var deleted bool = true
	this.Deleted = &deleted
	this.Id = id
	return &this
}

// NewDeleteAppRequestResponseWithDefaults instantiates a new DeleteAppRequestResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteAppRequestResponseWithDefaults() *DeleteAppRequestResponse {
	this := DeleteAppRequestResponse{}
	var deleted bool = true
	this.Deleted = &deleted
	return &this
}

// GetAccounts returns the Accounts field value if set, zero value otherwise.
func (o *DeleteAppRequestResponse) GetAccounts() int32 {
	if o == nil || IsNil(o.Accounts) {
		var ret int32
		return ret
	}
	return *o.Accounts
}

// GetAccountsOk returns a tuple with the Accounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteAppRequestResponse) GetAccountsOk() (*int32, bool) {
	if o == nil || IsNil(o.Accounts) {
		return nil, false
	}
	return o.Accounts, true
}

// HasAccounts returns a boolean if a field has been set.
func (o *DeleteAppRequestResponse) HasAccounts() bool {
	if o != nil && !IsNil(o.Accounts) {
		return true
	}

	return false
}

// SetAccounts gets a reference to the given int32 and assigns it to the Accounts field.
func (o *DeleteAppRequestResponse) SetAccounts(v int32) {
	o.Accounts = &v
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (o *DeleteAppRequestResponse) GetDeleted() bool {
	if o == nil || IsNil(o.Deleted) {
		var ret bool
		return ret
	}
	return *o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteAppRequestResponse) GetDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.Deleted) {
		return nil, false
	}
	return o.Deleted, true
}

// HasDeleted returns a boolean if a field has been set.
func (o *DeleteAppRequestResponse) HasDeleted() bool {
	if o != nil && !IsNil(o.Deleted) {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given bool and assigns it to the Deleted field.
func (o *DeleteAppRequestResponse) SetDeleted(v bool) {
	o.Deleted = &v
}

// GetId returns the Id field value
func (o *DeleteAppRequestResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DeleteAppRequestResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DeleteAppRequestResponse) SetId(v string) {
	o.Id = v
}

func (o DeleteAppRequestResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteAppRequestResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Accounts) {
		toSerialize["accounts"] = o.Accounts
	}
	if !IsNil(o.Deleted) {
		toSerialize["deleted"] = o.Deleted
	}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *DeleteAppRequestResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteAppRequestResponse := _DeleteAppRequestResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteAppRequestResponse)

	if err != nil {
		return err
	}

	*o = DeleteAppRequestResponse(varDeleteAppRequestResponse)

	return err
}

type NullableDeleteAppRequestResponse struct {
	value *DeleteAppRequestResponse
	isSet bool
}

func (v NullableDeleteAppRequestResponse) Get() *DeleteAppRequestResponse {
	return v.value
}

func (v *NullableDeleteAppRequestResponse) Set(val *DeleteAppRequestResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteAppRequestResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteAppRequestResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteAppRequestResponse(val *DeleteAppRequestResponse) *NullableDeleteAppRequestResponse {
	return &NullableDeleteAppRequestResponse{value: val, isSet: true}
}

func (v NullableDeleteAppRequestResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteAppRequestResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


