/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DiscoveredServerSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DiscoveredServerSettings{}

// DiscoveredServerSettings struct for DiscoveredServerSettings
type DiscoveredServerSettings struct {
	Auth *DetectedAuthenticationInfo `json:"auth,omitempty"`
	// Hostname to connect to
	Host string `json:"host"`
	// Service port number
	Port int32 `json:"port"`
	// Should connection use TLS. Usually true for port 993
	Secure *bool `json:"secure,omitempty"`
}

type _DiscoveredServerSettings DiscoveredServerSettings

// NewDiscoveredServerSettings instantiates a new DiscoveredServerSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDiscoveredServerSettings(host string, port int32) *DiscoveredServerSettings {
	this := DiscoveredServerSettings{}
	this.Host = host
	this.Port = port
	var secure bool = false
	this.Secure = &secure
	return &this
}

// NewDiscoveredServerSettingsWithDefaults instantiates a new DiscoveredServerSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiscoveredServerSettingsWithDefaults() *DiscoveredServerSettings {
	this := DiscoveredServerSettings{}
	var secure bool = false
	this.Secure = &secure
	return &this
}

// GetAuth returns the Auth field value if set, zero value otherwise.
func (o *DiscoveredServerSettings) GetAuth() DetectedAuthenticationInfo {
	if o == nil || IsNil(o.Auth) {
		var ret DetectedAuthenticationInfo
		return ret
	}
	return *o.Auth
}

// GetAuthOk returns a tuple with the Auth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiscoveredServerSettings) GetAuthOk() (*DetectedAuthenticationInfo, bool) {
	if o == nil || IsNil(o.Auth) {
		return nil, false
	}
	return o.Auth, true
}

// HasAuth returns a boolean if a field has been set.
func (o *DiscoveredServerSettings) HasAuth() bool {
	if o != nil && !IsNil(o.Auth) {
		return true
	}

	return false
}

// SetAuth gets a reference to the given DetectedAuthenticationInfo and assigns it to the Auth field.
func (o *DiscoveredServerSettings) SetAuth(v DetectedAuthenticationInfo) {
	o.Auth = &v
}

// GetHost returns the Host field value
func (o *DiscoveredServerSettings) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *DiscoveredServerSettings) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *DiscoveredServerSettings) SetHost(v string) {
	o.Host = v
}

// GetPort returns the Port field value
func (o *DiscoveredServerSettings) GetPort() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Port
}

// GetPortOk returns a tuple with the Port field value
// and a boolean to check if the value has been set.
func (o *DiscoveredServerSettings) GetPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Port, true
}

// SetPort sets field value
func (o *DiscoveredServerSettings) SetPort(v int32) {
	o.Port = v
}

// GetSecure returns the Secure field value if set, zero value otherwise.
func (o *DiscoveredServerSettings) GetSecure() bool {
	if o == nil || IsNil(o.Secure) {
		var ret bool
		return ret
	}
	return *o.Secure
}

// GetSecureOk returns a tuple with the Secure field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DiscoveredServerSettings) GetSecureOk() (*bool, bool) {
	if o == nil || IsNil(o.Secure) {
		return nil, false
	}
	return o.Secure, true
}

// HasSecure returns a boolean if a field has been set.
func (o *DiscoveredServerSettings) HasSecure() bool {
	if o != nil && !IsNil(o.Secure) {
		return true
	}

	return false
}

// SetSecure gets a reference to the given bool and assigns it to the Secure field.
func (o *DiscoveredServerSettings) SetSecure(v bool) {
	o.Secure = &v
}

func (o DiscoveredServerSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DiscoveredServerSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Auth) {
		toSerialize["auth"] = o.Auth
	}
	toSerialize["host"] = o.Host
	toSerialize["port"] = o.Port
	if !IsNil(o.Secure) {
		toSerialize["secure"] = o.Secure
	}
	return toSerialize, nil
}

func (o *DiscoveredServerSettings) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"host",
		"port",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDiscoveredServerSettings := _DiscoveredServerSettings{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDiscoveredServerSettings)

	if err != nil {
		return err
	}

	*o = DiscoveredServerSettings(varDiscoveredServerSettings)

	return err
}

type NullableDiscoveredServerSettings struct {
	value *DiscoveredServerSettings
	isSet bool
}

func (v NullableDiscoveredServerSettings) Get() *DiscoveredServerSettings {
	return v.value
}

func (v *NullableDiscoveredServerSettings) Set(val *DiscoveredServerSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableDiscoveredServerSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableDiscoveredServerSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiscoveredServerSettings(val *DiscoveredServerSettings) *NullableDiscoveredServerSettings {
	return &NullableDiscoveredServerSettings{value: val, isSet: true}
}

func (v NullableDiscoveredServerSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiscoveredServerSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


