/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the LicenseDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LicenseDetails{}

// LicenseDetails struct for LicenseDetails
type LicenseDetails struct {
	// Licensed application identifier
	Application *string `json:"application,omitempty"`
	// License creation date
	Created *string `json:"created,omitempty"`
	// Licensed hostname or environment
	Hostname *string `json:"hostname,omitempty"`
	// License key
	Key *string `json:"key,omitempty"`
	// Organization or individual the license is issued to
	LicensedTo *string `json:"licensedTo,omitempty"`
}

// NewLicenseDetails instantiates a new LicenseDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLicenseDetails() *LicenseDetails {
	this := LicenseDetails{}
	return &this
}

// NewLicenseDetailsWithDefaults instantiates a new LicenseDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLicenseDetailsWithDefaults() *LicenseDetails {
	this := LicenseDetails{}
	return &this
}

// GetApplication returns the Application field value if set, zero value otherwise.
func (o *LicenseDetails) GetApplication() string {
	if o == nil || IsNil(o.Application) {
		var ret string
		return ret
	}
	return *o.Application
}

// GetApplicationOk returns a tuple with the Application field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LicenseDetails) GetApplicationOk() (*string, bool) {
	if o == nil || IsNil(o.Application) {
		return nil, false
	}
	return o.Application, true
}

// HasApplication returns a boolean if a field has been set.
func (o *LicenseDetails) HasApplication() bool {
	if o != nil && !IsNil(o.Application) {
		return true
	}

	return false
}

// SetApplication gets a reference to the given string and assigns it to the Application field.
func (o *LicenseDetails) SetApplication(v string) {
	o.Application = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *LicenseDetails) GetCreated() string {
	if o == nil || IsNil(o.Created) {
		var ret string
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LicenseDetails) GetCreatedOk() (*string, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *LicenseDetails) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given string and assigns it to the Created field.
func (o *LicenseDetails) SetCreated(v string) {
	o.Created = &v
}

// GetHostname returns the Hostname field value if set, zero value otherwise.
func (o *LicenseDetails) GetHostname() string {
	if o == nil || IsNil(o.Hostname) {
		var ret string
		return ret
	}
	return *o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LicenseDetails) GetHostnameOk() (*string, bool) {
	if o == nil || IsNil(o.Hostname) {
		return nil, false
	}
	return o.Hostname, true
}

// HasHostname returns a boolean if a field has been set.
func (o *LicenseDetails) HasHostname() bool {
	if o != nil && !IsNil(o.Hostname) {
		return true
	}

	return false
}

// SetHostname gets a reference to the given string and assigns it to the Hostname field.
func (o *LicenseDetails) SetHostname(v string) {
	o.Hostname = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *LicenseDetails) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LicenseDetails) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *LicenseDetails) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *LicenseDetails) SetKey(v string) {
	o.Key = &v
}

// GetLicensedTo returns the LicensedTo field value if set, zero value otherwise.
func (o *LicenseDetails) GetLicensedTo() string {
	if o == nil || IsNil(o.LicensedTo) {
		var ret string
		return ret
	}
	return *o.LicensedTo
}

// GetLicensedToOk returns a tuple with the LicensedTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LicenseDetails) GetLicensedToOk() (*string, bool) {
	if o == nil || IsNil(o.LicensedTo) {
		return nil, false
	}
	return o.LicensedTo, true
}

// HasLicensedTo returns a boolean if a field has been set.
func (o *LicenseDetails) HasLicensedTo() bool {
	if o != nil && !IsNil(o.LicensedTo) {
		return true
	}

	return false
}

// SetLicensedTo gets a reference to the given string and assigns it to the LicensedTo field.
func (o *LicenseDetails) SetLicensedTo(v string) {
	o.LicensedTo = &v
}

func (o LicenseDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LicenseDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Application) {
		toSerialize["application"] = o.Application
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Hostname) {
		toSerialize["hostname"] = o.Hostname
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.LicensedTo) {
		toSerialize["licensedTo"] = o.LicensedTo
	}
	return toSerialize, nil
}

type NullableLicenseDetails struct {
	value *LicenseDetails
	isSet bool
}

func (v NullableLicenseDetails) Get() *LicenseDetails {
	return v.value
}

func (v *NullableLicenseDetails) Set(val *LicenseDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableLicenseDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableLicenseDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLicenseDetails(val *LicenseDetails) *NullableLicenseDetails {
	return &NullableLicenseDetails{value: val, isSet: true}
}

func (v NullableLicenseDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLicenseDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


