/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the TextInfoDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TextInfoDetails{}

// TextInfoDetails struct for TextInfoDetails
type TextInfoDetails struct {
	EncodedSize *EncodedSize `json:"encodedSize,omitempty"`
	// Whether the message content was truncated (true if more content is available via separate API call)
	HasMore *bool `json:"hasMore,omitempty"`
	// HTML version of the message
	Html *string `json:"html,omitempty"`
	// Identifier for fetching additional text content
	Id *string `json:"id,omitempty"`
	// Plain text version of the message
	Plain *string `json:"plain,omitempty"`
}

// NewTextInfoDetails instantiates a new TextInfoDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTextInfoDetails() *TextInfoDetails {
	this := TextInfoDetails{}
	return &this
}

// NewTextInfoDetailsWithDefaults instantiates a new TextInfoDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTextInfoDetailsWithDefaults() *TextInfoDetails {
	this := TextInfoDetails{}
	return &this
}

// GetEncodedSize returns the EncodedSize field value if set, zero value otherwise.
func (o *TextInfoDetails) GetEncodedSize() EncodedSize {
	if o == nil || IsNil(o.EncodedSize) {
		var ret EncodedSize
		return ret
	}
	return *o.EncodedSize
}

// GetEncodedSizeOk returns a tuple with the EncodedSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextInfoDetails) GetEncodedSizeOk() (*EncodedSize, bool) {
	if o == nil || IsNil(o.EncodedSize) {
		return nil, false
	}
	return o.EncodedSize, true
}

// HasEncodedSize returns a boolean if a field has been set.
func (o *TextInfoDetails) HasEncodedSize() bool {
	if o != nil && !IsNil(o.EncodedSize) {
		return true
	}

	return false
}

// SetEncodedSize gets a reference to the given EncodedSize and assigns it to the EncodedSize field.
func (o *TextInfoDetails) SetEncodedSize(v EncodedSize) {
	o.EncodedSize = &v
}

// GetHasMore returns the HasMore field value if set, zero value otherwise.
func (o *TextInfoDetails) GetHasMore() bool {
	if o == nil || IsNil(o.HasMore) {
		var ret bool
		return ret
	}
	return *o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextInfoDetails) GetHasMoreOk() (*bool, bool) {
	if o == nil || IsNil(o.HasMore) {
		return nil, false
	}
	return o.HasMore, true
}

// HasHasMore returns a boolean if a field has been set.
func (o *TextInfoDetails) HasHasMore() bool {
	if o != nil && !IsNil(o.HasMore) {
		return true
	}

	return false
}

// SetHasMore gets a reference to the given bool and assigns it to the HasMore field.
func (o *TextInfoDetails) SetHasMore(v bool) {
	o.HasMore = &v
}

// GetHtml returns the Html field value if set, zero value otherwise.
func (o *TextInfoDetails) GetHtml() string {
	if o == nil || IsNil(o.Html) {
		var ret string
		return ret
	}
	return *o.Html
}

// GetHtmlOk returns a tuple with the Html field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextInfoDetails) GetHtmlOk() (*string, bool) {
	if o == nil || IsNil(o.Html) {
		return nil, false
	}
	return o.Html, true
}

// HasHtml returns a boolean if a field has been set.
func (o *TextInfoDetails) HasHtml() bool {
	if o != nil && !IsNil(o.Html) {
		return true
	}

	return false
}

// SetHtml gets a reference to the given string and assigns it to the Html field.
func (o *TextInfoDetails) SetHtml(v string) {
	o.Html = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TextInfoDetails) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextInfoDetails) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TextInfoDetails) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TextInfoDetails) SetId(v string) {
	o.Id = &v
}

// GetPlain returns the Plain field value if set, zero value otherwise.
func (o *TextInfoDetails) GetPlain() string {
	if o == nil || IsNil(o.Plain) {
		var ret string
		return ret
	}
	return *o.Plain
}

// GetPlainOk returns a tuple with the Plain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TextInfoDetails) GetPlainOk() (*string, bool) {
	if o == nil || IsNil(o.Plain) {
		return nil, false
	}
	return o.Plain, true
}

// HasPlain returns a boolean if a field has been set.
func (o *TextInfoDetails) HasPlain() bool {
	if o != nil && !IsNil(o.Plain) {
		return true
	}

	return false
}

// SetPlain gets a reference to the given string and assigns it to the Plain field.
func (o *TextInfoDetails) SetPlain(v string) {
	o.Plain = &v
}

func (o TextInfoDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TextInfoDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EncodedSize) {
		toSerialize["encodedSize"] = o.EncodedSize
	}
	if !IsNil(o.HasMore) {
		toSerialize["hasMore"] = o.HasMore
	}
	if !IsNil(o.Html) {
		toSerialize["html"] = o.Html
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Plain) {
		toSerialize["plain"] = o.Plain
	}
	return toSerialize, nil
}

type NullableTextInfoDetails struct {
	value *TextInfoDetails
	isSet bool
}

func (v NullableTextInfoDetails) Get() *TextInfoDetails {
	return v.value
}

func (v *NullableTextInfoDetails) Set(val *TextInfoDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableTextInfoDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableTextInfoDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTextInfoDetails(val *TextInfoDetails) *NullableTextInfoDetails {
	return &NullableTextInfoDetails{value: val, isSet: true}
}

func (v NullableTextInfoDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTextInfoDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


