/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SettingsPutQueueResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SettingsPutQueueResponse{}

// SettingsPutQueueResponse struct for SettingsPutQueueResponse
type SettingsPutQueueResponse struct {
	// Is the queue paused or not
	Paused *bool `json:"paused,omitempty"`
	Queue Queue `json:"queue"`
}

type _SettingsPutQueueResponse SettingsPutQueueResponse

// NewSettingsPutQueueResponse instantiates a new SettingsPutQueueResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSettingsPutQueueResponse(queue Queue) *SettingsPutQueueResponse {
	this := SettingsPutQueueResponse{}
	this.Queue = queue
	return &this
}

// NewSettingsPutQueueResponseWithDefaults instantiates a new SettingsPutQueueResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSettingsPutQueueResponseWithDefaults() *SettingsPutQueueResponse {
	this := SettingsPutQueueResponse{}
	return &this
}

// GetPaused returns the Paused field value if set, zero value otherwise.
func (o *SettingsPutQueueResponse) GetPaused() bool {
	if o == nil || IsNil(o.Paused) {
		var ret bool
		return ret
	}
	return *o.Paused
}

// GetPausedOk returns a tuple with the Paused field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SettingsPutQueueResponse) GetPausedOk() (*bool, bool) {
	if o == nil || IsNil(o.Paused) {
		return nil, false
	}
	return o.Paused, true
}

// HasPaused returns a boolean if a field has been set.
func (o *SettingsPutQueueResponse) HasPaused() bool {
	if o != nil && !IsNil(o.Paused) {
		return true
	}

	return false
}

// SetPaused gets a reference to the given bool and assigns it to the Paused field.
func (o *SettingsPutQueueResponse) SetPaused(v bool) {
	o.Paused = &v
}

// GetQueue returns the Queue field value
func (o *SettingsPutQueueResponse) GetQueue() Queue {
	if o == nil {
		var ret Queue
		return ret
	}

	return o.Queue
}

// GetQueueOk returns a tuple with the Queue field value
// and a boolean to check if the value has been set.
func (o *SettingsPutQueueResponse) GetQueueOk() (*Queue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Queue, true
}

// SetQueue sets field value
func (o *SettingsPutQueueResponse) SetQueue(v Queue) {
	o.Queue = v
}

func (o SettingsPutQueueResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SettingsPutQueueResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Paused) {
		toSerialize["paused"] = o.Paused
	}
	toSerialize["queue"] = o.Queue
	return toSerialize, nil
}

func (o *SettingsPutQueueResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"queue",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSettingsPutQueueResponse := _SettingsPutQueueResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSettingsPutQueueResponse)

	if err != nil {
		return err
	}

	*o = SettingsPutQueueResponse(varSettingsPutQueueResponse)

	return err
}

type NullableSettingsPutQueueResponse struct {
	value *SettingsPutQueueResponse
	isSet bool
}

func (v NullableSettingsPutQueueResponse) Get() *SettingsPutQueueResponse {
	return v.value
}

func (v *NullableSettingsPutQueueResponse) Set(val *SettingsPutQueueResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSettingsPutQueueResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSettingsPutQueueResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSettingsPutQueueResponse(val *SettingsPutQueueResponse) *NullableSettingsPutQueueResponse {
	return &NullableSettingsPutQueueResponse{value: val, isSet: true}
}

func (v NullableSettingsPutQueueResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSettingsPutQueueResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


