/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BlocklistListAddPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlocklistListAddPayload{}

// BlocklistListAddPayload struct for BlocklistListAddPayload
type BlocklistListAddPayload struct {
	// Unique identifier for the email account
	Account string `json:"account"`
	// Identifier for the blocking reason
	Reason *string `json:"reason,omitempty"`
	// Email address to add to the list
	Recipient string `json:"recipient"`
}

type _BlocklistListAddPayload BlocklistListAddPayload

// NewBlocklistListAddPayload instantiates a new BlocklistListAddPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlocklistListAddPayload(account string, recipient string) *BlocklistListAddPayload {
	this := BlocklistListAddPayload{}
	this.Account = account
	var reason string = "block"
	this.Reason = &reason
	this.Recipient = recipient
	return &this
}

// NewBlocklistListAddPayloadWithDefaults instantiates a new BlocklistListAddPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlocklistListAddPayloadWithDefaults() *BlocklistListAddPayload {
	this := BlocklistListAddPayload{}
	var reason string = "block"
	this.Reason = &reason
	return &this
}

// GetAccount returns the Account field value
func (o *BlocklistListAddPayload) GetAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Account
}

// GetAccountOk returns a tuple with the Account field value
// and a boolean to check if the value has been set.
func (o *BlocklistListAddPayload) GetAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Account, true
}

// SetAccount sets field value
func (o *BlocklistListAddPayload) SetAccount(v string) {
	o.Account = v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *BlocklistListAddPayload) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BlocklistListAddPayload) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *BlocklistListAddPayload) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *BlocklistListAddPayload) SetReason(v string) {
	o.Reason = &v
}

// GetRecipient returns the Recipient field value
func (o *BlocklistListAddPayload) GetRecipient() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Recipient
}

// GetRecipientOk returns a tuple with the Recipient field value
// and a boolean to check if the value has been set.
func (o *BlocklistListAddPayload) GetRecipientOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Recipient, true
}

// SetRecipient sets field value
func (o *BlocklistListAddPayload) SetRecipient(v string) {
	o.Recipient = v
}

func (o BlocklistListAddPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlocklistListAddPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["account"] = o.Account
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	toSerialize["recipient"] = o.Recipient
	return toSerialize, nil
}

func (o *BlocklistListAddPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"account",
		"recipient",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBlocklistListAddPayload := _BlocklistListAddPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBlocklistListAddPayload)

	if err != nil {
		return err
	}

	*o = BlocklistListAddPayload(varBlocklistListAddPayload)

	return err
}

type NullableBlocklistListAddPayload struct {
	value *BlocklistListAddPayload
	isSet bool
}

func (v NullableBlocklistListAddPayload) Get() *BlocklistListAddPayload {
	return v.value
}

func (v *NullableBlocklistListAddPayload) Set(val *BlocklistListAddPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableBlocklistListAddPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableBlocklistListAddPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlocklistListAddPayload(val *BlocklistListAddPayload) *NullableBlocklistListAddPayload {
	return &NullableBlocklistListAddPayload{value: val, isSet: true}
}

func (v NullableBlocklistListAddPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlocklistListAddPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


