/*
EmailEngine API

EmailEngine provides a RESTful API for managing email accounts, sending messages, and processing email data across multiple providers.  <h3>Authentication</h3> All API requests require authentication using an Access Token. You can generate and manage your tokens from the <a href=\"/admin/tokens\" target=\"_parent\"><strong>Access Tokens</strong></a> page.  Include your token in requests using one of these methods: - Query parameter: <code>?access_token=YOUR_TOKEN</code> - Authorization header: <code>Authorization: Bearer YOUR_TOKEN</code>  <h3>Request Processing</h3>  <strong>Sequential Processing:</strong> Requests to the same email account are processed sequentially to maintain data consistency. Multiple simultaneous requests will be queued.  <strong>Timeouts:</strong> Long-running operations may cause queued requests to timeout. Configure appropriate timeout values using the <code>X-EE-Timeout</code> header (in milliseconds).  <h3>Getting Started</h3> 1. <a href=\"/admin/tokens\" target=\"_parent\">Generate an Access Token</a> 2. <a href=\"/admin/accounts\" target=\"_parent\">Add an email account</a> 3. Start making API requests using the endpoints below

API version: 2.61.1
Contact: support@emailengine.app
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ModifyMailbox type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModifyMailbox{}

// ModifyMailbox struct for ModifyMailbox
type ModifyMailbox struct {
	// New mailbox path as an array or a string. If account is namespaced then namespace prefix is added by default. Optional.
	NewPath []string `json:"newPath,omitempty"`
	// Mailbox folder path to modify
	Path string `json:"path"`
	// Change mailbox subscription status. Only applies to IMAP accounts, ignored for Gmail and Outlook.
	Subscribed *bool `json:"subscribed,omitempty"`
}

type _ModifyMailbox ModifyMailbox

// NewModifyMailbox instantiates a new ModifyMailbox object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModifyMailbox(path string) *ModifyMailbox {
	this := ModifyMailbox{}
	this.Path = path
	return &this
}

// NewModifyMailboxWithDefaults instantiates a new ModifyMailbox object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModifyMailboxWithDefaults() *ModifyMailbox {
	this := ModifyMailbox{}
	return &this
}

// GetNewPath returns the NewPath field value if set, zero value otherwise.
func (o *ModifyMailbox) GetNewPath() []string {
	if o == nil || IsNil(o.NewPath) {
		var ret []string
		return ret
	}
	return o.NewPath
}

// GetNewPathOk returns a tuple with the NewPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModifyMailbox) GetNewPathOk() ([]string, bool) {
	if o == nil || IsNil(o.NewPath) {
		return nil, false
	}
	return o.NewPath, true
}

// HasNewPath returns a boolean if a field has been set.
func (o *ModifyMailbox) HasNewPath() bool {
	if o != nil && !IsNil(o.NewPath) {
		return true
	}

	return false
}

// SetNewPath gets a reference to the given []string and assigns it to the NewPath field.
func (o *ModifyMailbox) SetNewPath(v []string) {
	o.NewPath = v
}

// GetPath returns the Path field value
func (o *ModifyMailbox) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *ModifyMailbox) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *ModifyMailbox) SetPath(v string) {
	o.Path = v
}

// GetSubscribed returns the Subscribed field value if set, zero value otherwise.
func (o *ModifyMailbox) GetSubscribed() bool {
	if o == nil || IsNil(o.Subscribed) {
		var ret bool
		return ret
	}
	return *o.Subscribed
}

// GetSubscribedOk returns a tuple with the Subscribed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModifyMailbox) GetSubscribedOk() (*bool, bool) {
	if o == nil || IsNil(o.Subscribed) {
		return nil, false
	}
	return o.Subscribed, true
}

// HasSubscribed returns a boolean if a field has been set.
func (o *ModifyMailbox) HasSubscribed() bool {
	if o != nil && !IsNil(o.Subscribed) {
		return true
	}

	return false
}

// SetSubscribed gets a reference to the given bool and assigns it to the Subscribed field.
func (o *ModifyMailbox) SetSubscribed(v bool) {
	o.Subscribed = &v
}

func (o ModifyMailbox) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModifyMailbox) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NewPath) {
		toSerialize["newPath"] = o.NewPath
	}
	toSerialize["path"] = o.Path
	if !IsNil(o.Subscribed) {
		toSerialize["subscribed"] = o.Subscribed
	}
	return toSerialize, nil
}

func (o *ModifyMailbox) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"path",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModifyMailbox := _ModifyMailbox{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varModifyMailbox)

	if err != nil {
		return err
	}

	*o = ModifyMailbox(varModifyMailbox)

	return err
}

type NullableModifyMailbox struct {
	value *ModifyMailbox
	isSet bool
}

func (v NullableModifyMailbox) Get() *ModifyMailbox {
	return v.value
}

func (v *NullableModifyMailbox) Set(val *ModifyMailbox) {
	v.value = val
	v.isSet = true
}

func (v NullableModifyMailbox) IsSet() bool {
	return v.isSet
}

func (v *NullableModifyMailbox) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModifyMailbox(val *ModifyMailbox) *NullableModifyMailbox {
	return &NullableModifyMailbox{value: val, isSet: true}
}

func (v NullableModifyMailbox) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModifyMailbox) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


